// Word types for dictionary words, keyed by the exact written form.
// Looked up by text, so it also covers anything else spelled the same way.
//
// Verbs: the godan verbs that look like ichidan are listed by hand; the
// rest are classified by their ending (see gen_verb_types in the notes).
// Mirrors kWordTypes in chrome_extension/shared.js - keep the two in sync.
const Map<String, String> kWordTypes = {
  '脂ぎる': 'Godan Verb',
  '油ぎる': 'Godan Verb',
  'びびる': 'Godan Verb',
  '千切る': 'Godan Verb',
  '散る': 'Godan Verb',
  'どじる': 'Godan Verb',
  '愚痴る': 'Godan Verb',
  '入る': 'Godan Verb',
  '走る': 'Godan Verb',
  '穿る': 'Godan Verb',
  '迸る': 'Godan Verb',
  'いびる': 'Godan Verb',
  '弄る': 'Godan Verb',
  '煎る': 'Godan Verb',
  '炒る': 'Godan Verb',
  '熬る': 'Godan Verb',
  '要る': 'Godan Verb',
  '限る': 'Godan Verb',
  '噛る': 'Godan Verb',
  '切る': 'Godan Verb',
  '軋る': 'Godan Verb',
  '轢る': 'Godan Verb',
  '輾る': 'Godan Verb',
  '抉じる': 'Godan Verb',
  '参る': 'Godan Verb',
  '混じる': 'Godan Verb',
  '滅入る': 'Godan Verb',
  '漲る': 'Godan Verb',
  '毟る': 'Godan Verb',
  '挘る': 'Godan Verb',
  '詰る': 'Godan Verb',
  'ねじる': 'Godan Verb',
  '握る': 'Godan Verb',
  '罵る': 'Godan Verb',
  '陥る': 'Godan Verb',
  'せびる': 'Godan Verb',
  '知る': 'Godan Verb',
  '謗る': 'Godan Verb',
  '譏る': 'Godan Verb',
  '誹る': 'Godan Verb',
  '滾る': 'Godan Verb',
  '激る': 'Godan Verb',
  '魂消る': 'Godan Verb',
  'やじる': 'Godan Verb',
  '攀じる': 'Godan Verb',
  '焦る': 'Godan Verb',
  'ふける': 'Godan Verb',
  '伏せる': 'Godan Verb',
  '減る': 'Godan Verb',
  '捻る': 'Godan Verb',
  '火照る': 'Godan Verb',
  '帰る': 'Godan Verb',
  '陰る': 'Godan Verb',
  '翔る': 'Godan Verb',
  '蹴る': 'Godan Verb',
  'くねる': 'Godan Verb',
  '覆る': 'Godan Verb',
  '練る': 'Godan Verb',
  '煉る': 'Godan Verb',
  'のめる': 'Godan Verb',
  '滑る': 'Godan Verb',
  '阿る': 'Godan Verb',
  '阿ねる': 'Godan Verb',
  '競る': 'Godan Verb',
  '糶る': 'Godan Verb',
  '挵る': 'Godan Verb',
  '喋る': 'Godan Verb',
  '茂る': 'Godan Verb',
  '繁る': 'Godan Verb',
  '滋る': 'Godan Verb',
  '湿気る': 'Godan Verb',
  '猛る': 'Godan Verb',
  '照る': 'Godan Verb',
  '詰める': 'Godan Verb',
  '抓る': 'Godan Verb',
  '畝る': 'Godan Verb',
  '蘇る': 'Godan Verb',
  '行く': 'Godan Verb',
  'やる': 'Godan Verb',
  '持つ': 'Godan Verb',
  '思う': 'Godan Verb',
  '飲む': 'Godan Verb',
  '作る': 'Godan Verb',
  '聞く': 'Godan Verb',
  '書く': 'Godan Verb',
  '使う': 'Godan Verb',
  '話す': 'Godan Verb',
  '買う': 'Godan Verb',
  '払う': 'Godan Verb',
  '終わる': 'Godan Verb',
  '違う': 'Godan Verb',
  '乗る': 'Godan Verb',
  '置く': 'Godan Verb',
  '残る': 'Godan Verb',
  '会う': 'Godan Verb',
  '立つ': 'Godan Verb',
  '座る': 'Godan Verb',
  'なる': 'Godan Verb',
  'ある': 'Godan Verb',
  '言う': 'Godan Verb',
  '読む': 'Godan Verb',
  '出す': 'Godan Verb',
  '取る': 'Godan Verb',
  '呼ぶ': 'Godan Verb',
  '売る': 'Godan Verb',
  '押す': 'Godan Verb',
  '渡す': 'Godan Verb',
  '歌う': 'Godan Verb',
  '待つ': 'Godan Verb',
  '貼る': 'Godan Verb',
  '始まる': 'Godan Verb',
  '返す': 'Godan Verb',
  'わかる': 'Godan Verb',
  '遊ぶ': 'Godan Verb',
  '撮る': 'Godan Verb',
  '休む': 'Godan Verb',
  '洗う': 'Godan Verb',
  '消す': 'Godan Verb',
  '曲がる': 'Godan Verb',
  '泳ぐ': 'Godan Verb',
  '降る': 'Godan Verb',
  '並ぶ': 'Godan Verb',
  'かかる': 'Godan Verb',
  '困る': 'Godan Verb',
  '開く': 'Godan Verb',
  '吸う': 'Godan Verb',
  '貸す': 'Godan Verb',
  '働く': 'Godan Verb',
  '死ぬ': 'Godan Verb',
  '渡る': 'Godan Verb',
  '住む': 'Godan Verb',
  '歩く': 'Godan Verb',
  '習う': 'Godan Verb',
  '履く': 'Godan Verb',
  '引く': 'Godan Verb',
  '差す': 'Godan Verb',
  '飛ぶ': 'Godan Verb',
  '着く': 'Godan Verb',
  '脱ぐ': 'Godan Verb',
  '閉まる': 'Godan Verb',
  '登る': 'Godan Verb',
  '無くす': 'Godan Verb',
  '咲く': 'Godan Verb',
  '吹く': 'Godan Verb',
  '弾く': 'Godan Verb',
  '鳴く': 'Godan Verb',
  '磨く': 'Godan Verb',
  '曇る': 'Godan Verb',
  '連絡': 'Godan Verb',
  '探す': 'Godan Verb',
  '選ぶ': 'Godan Verb',
  '変わる': 'Godan Verb',
  '行う': 'Godan Verb',
  '送る': 'Godan Verb',
  '戻る': 'Godan Verb',
  '合う': 'Godan Verb',
  'ご覧になる': 'Godan Verb',
  '見つかる': 'Godan Verb',
  '運ぶ': 'Godan Verb',
  '打つ': 'Godan Verb',
  '決まる': 'Godan Verb',
  '起こす': 'Godan Verb',
  '上がる': 'Godan Verb',
  '通る': 'Godan Verb',
  '包む': 'Godan Verb',
  '思い出す': 'Godan Verb',
  '落とす': 'Godan Verb',
  '飾る': 'Godan Verb',
  '喜ぶ': 'Godan Verb',
  '楽しむ': 'Godan Verb',
  '向かう': 'Godan Verb',
  '進む': 'Godan Verb',
  '盗む': 'Godan Verb',
  '通う': 'Godan Verb',
  '間に合う': 'Godan Verb',
  '騒ぐ': 'Godan Verb',
  '笑う': 'Godan Verb',
  '集まる': 'Godan Verb',
  '役に立つ': 'Godan Verb',
  '引っ越す': 'Godan Verb',
  '壊す': 'Godan Verb',
  '怒る': 'Godan Verb',
  '踏む': 'Godan Verb',
  '光る': 'Godan Verb',
  '下がる': 'Godan Verb',
  '急ぐ': 'Godan Verb',
  '直る': 'Godan Verb',
  '勝つ': 'Godan Verb',
  '申す': 'Godan Verb',
  '引き出す': 'Godan Verb',
  '写す': 'Godan Verb',
  '治る': 'Godan Verb',
  '塗る': 'Godan Verb',
  '泊まる': 'Godan Verb',
  '致す': 'Godan Verb',
  '沸かす': 'Godan Verb',
  '済む': 'Godan Verb',
  '続く': 'Godan Verb',
  '謝る': 'Godan Verb',
  '触る': 'Godan Verb',
  '釣る': 'Godan Verb',
  '眠る': 'Godan Verb',
  '足す': 'Godan Verb',
  '移る': 'Godan Verb',
  '動く': 'Godan Verb',
  '折る': 'Godan Verb',
  '込む': 'Godan Verb',
  '鳴る': 'Godan Verb',
  'いらっしゃる': 'Godan Verb',
  'ござる': 'Godan Verb',
  '御座る': 'Godan Verb',
  '回る': 'Godan Verb',
  '拾う': 'Godan Verb',
  '付く': 'Godan Verb',
  '直す': 'Godan Verb',
  '驚く': 'Godan Verb',
  '太る': 'Godan Verb',
  'おっしゃる': 'Godan Verb',
  'なさる': 'Godan Verb',
  '無くなる': 'Godan Verb',
  '寄る': 'Godan Verb',
  '手伝う': 'Godan Verb',
  '焼く': 'Godan Verb',
  '泣く': 'Godan Verb',
  '止む': 'Godan Verb',
  '降り出す': 'Godan Verb',
  '踊る': 'Godan Verb',
  '祈る': 'Godan Verb',
  '亡くなる': 'Godan Verb',
  'おいでになる': 'Godan Verb',
  '乾く': 'Godan Verb',
  '噛む': 'Godan Verb',
  '召し上がる': 'Godan Verb',
  '沸く': 'Godan Verb',
  '治す': 'Godan Verb',
  '成る': 'Godan Verb',
  '為る': 'Godan Verb',
  '異なる': 'Godan Verb',
  '語る': 'Godan Verb',
  '除く': 'Godan Verb',
  '残す': 'Godan Verb',
  '含む': 'Godan Verb',
  '守る': 'Godan Verb',
  '示す': 'Godan Verb',
  '基づく': 'Godan Verb',
  '殺す': 'Godan Verb',
  '受け取る': 'Godan Verb',
  '追う': 'Godan Verb',
  '失う': 'Godan Verb',
  '結ぶ': 'Godan Verb',
  '流す': 'Godan Verb',
  '贈る': 'Godan Verb',
  '起こる': 'Godan Verb',
  '繰り返す': 'Godan Verb',
  '奪う': 'Godan Verb',
  '囲む': 'Godan Verb',
  '支払う': 'Godan Verb',
  '断る': 'Godan Verb',
  '望む': 'Godan Verb',
  '外す': 'Godan Verb',
  '隠す': 'Godan Verb',
  '学ぶ': 'Godan Verb',
  '話し合う': 'Godan Verb',
  'おる': 'Godan Verb',
  '誘う': 'Godan Verb',
  '回す': 'Godan Verb',
  '飛び出す': 'Godan Verb',
  '扱う': 'Godan Verb',
  '動かす': 'Godan Verb',
  '撃つ': 'Godan Verb',
  '張る': 'Godan Verb',
  '出会う': 'Godan Verb',
  '叫ぶ': 'Godan Verb',
  '組む': 'Godan Verb',
  '移す': 'Godan Verb',
  '黙る': 'Godan Verb',
  '覆う': 'Godan Verb',
  '疑う': 'Godan Verb',
  'くださる': 'Godan Verb',
  '好む': 'Godan Verb',
  '救う': 'Godan Verb',
  '頼る': 'Godan Verb',
  '破る': 'Godan Verb',
  '悩む': 'Godan Verb',
  '試す': 'Godan Verb',
  '裏切る': 'Godan Verb',
  '構う': 'Godan Verb',
  '嫌う': 'Godan Verb',
  '引っ張る': 'Godan Verb',
  '戻す': 'Godan Verb',
  '注ぐ': 'Godan Verb',
  '防ぐ': 'Godan Verb',
  '減らす': 'Godan Verb',
  '育つ': 'Godan Verb',
  '当たる': 'Godan Verb',
  '加わる': 'Godan Verb',
  '似合う': 'Godan Verb',
  '過ごす': 'Godan Verb',
  '倒す': 'Godan Verb',
  'しまう': 'Godan Verb',
  '飛ばす': 'Godan Verb',
  '追いつく': 'Godan Verb',
  '広がる': 'Godan Verb',
  '割る': 'Godan Verb',
  '悲しむ': 'Godan Verb',
  '祝う': 'Godan Verb',
  '気づく': 'Godan Verb',
  '去る': 'Godan Verb',
  '刈る': 'Godan Verb',
  '雇う': 'Godan Verb',
  '願う': 'Godan Verb',
  '頂く': 'Godan Verb',
  '食う': 'Godan Verb',
  '飼う': 'Godan Verb',
  '離す': 'Godan Verb',
  '及ぼす': 'Godan Verb',
  '狂う': 'Godan Verb',
  '越す': 'Godan Verb',
  '劣る': 'Godan Verb',
  '暮らす': 'Godan Verb',
  '至る': 'Godan Verb',
  '申し込む': 'Godan Verb',
  '転ぶ': 'Godan Verb',
  '表す': 'Godan Verb',
  '経つ': 'Godan Verb',
  '横切る': 'Godan Verb',
  '積もる': 'Godan Verb',
  '立ち上がる': 'Godan Verb',
  '凍る': 'Godan Verb',
  '振る': 'Godan Verb',
  '指す': 'Godan Verb',
  '貰う': 'Godan Verb',
  '届く': 'Godan Verb',
  '描く': 'Godan Verb',
  '腐る': 'Godan Verb',
  '気に入る': 'Godan Verb',
  '伸ばす': 'Godan Verb',
  '掛かる': 'Godan Verb',
  '稼ぐ': 'Godan Verb',
  '戦う': 'Godan Verb',
  '輝く': 'Godan Verb',
  '沈む': 'Godan Verb',
  '逆らう': 'Godan Verb',
  '酔う': 'Godan Verb',
  '増す': 'Godan Verb',
  '覚ます': 'Godan Verb',
  '譲る': 'Godan Verb',
  '苦しむ': 'Godan Verb',
  '通す': 'Godan Verb',
  '効く': 'Godan Verb',
  '抜く': 'Godan Verb',
  '解く': 'Godan Verb',
  '向く': 'Godan Verb',
  'よす': 'Godan Verb',
  '下ろす': 'Godan Verb',
  '被る': 'Godan Verb',
  '捕まる': 'Godan Verb',
  '従う': 'Godan Verb',
  '抱く': 'Godan Verb',
  '放す': 'Godan Verb',
  '計る': 'Godan Verb',
  '空く': 'Godan Verb',
  '省く': 'Godan Verb',
  '招く': 'Godan Verb',
  '叩く': 'Godan Verb',
  '唸る': 'Godan Verb',
  '微笑む': 'Godan Verb',
  '吐く': 'Godan Verb',
  '降ろす': 'Godan Verb',
  '昇る': 'Godan Verb',
  '就く': 'Godan Verb',
  '繋ぐ': 'Godan Verb',
  '伺う': 'Godan Verb',
  '掴む': 'Godan Verb',
  '叱る': 'Godan Verb',
  '罹る': 'Godan Verb',
  '轢く': 'Godan Verb',
  '捜す': 'Godan Verb',
  '造る': 'Godan Verb',
  '迫る': 'Godan Verb',
  '在る': 'Godan Verb',
  '生る': 'Godan Verb',
  'くるむ': 'Godan Verb',
  '見送る': 'Godan Verb',
  '見直す': 'Godan Verb',
  '放る': 'Godan Verb',
  '争う': 'Godan Verb',
  '物語る': 'Godan Verb',
  '狙う': 'Godan Verb',
  '止まる': 'Godan Verb',
  '絞る': 'Godan Verb',
  '配る': 'Godan Verb',
  '次ぐ': 'Godan Verb',
  '伝わる': 'Godan Verb',
  '刻む': 'Godan Verb',
  '下る': 'Godan Verb',
  '殴る': 'Godan Verb',
  '深まる': 'Godan Verb',
  '見舞う': 'Godan Verb',
  '建つ': 'Godan Verb',
  '積む': 'Godan Verb',
  '討つ': 'Godan Verb',
  '余る': 'Godan Verb',
  '写る': 'Godan Verb',
  '縛る': 'Godan Verb',
  '詰まる': 'Godan Verb',
  '目指す': 'Godan Verb',
  '味わう': 'Godan Verb',
  '取り消す': 'Godan Verb',
  '盛る': 'Godan Verb',
  '刺す': 'Godan Verb',
  '驚かす': 'Godan Verb',
  '膨らむ': 'Godan Verb',
  '発つ': 'Godan Verb',
  '締め切る': 'Godan Verb',
  '巡る': 'Godan Verb',
  '削る': 'Godan Verb',
  '呼び出す': 'Godan Verb',
  '整う': 'Godan Verb',
  '冷やす': 'Godan Verb',
  '慶ぶ': 'Godan Verb',
  '干す': 'Godan Verb',
  '膨らます': 'Godan Verb',
  '足る': 'Godan Verb',
  '映る': 'Godan Verb',
  '刺さる': 'Godan Verb',
  '浮かぶ': 'Godan Verb',
  '占う': 'Godan Verb',
  '蒸す': 'Godan Verb',
  '転がる': 'Godan Verb',
  '預かる': 'Godan Verb',
  '感ずる': 'Godan Verb',
  '転がす': 'Godan Verb',
  '挟む': 'Godan Verb',
  '代わる': 'Godan Verb',
  '論ずる': 'Godan Verb',
  '目立つ': 'Godan Verb',
  '突っこむ': 'Godan Verb',
  '遭う': 'Godan Verb',
  '溶かす': 'Godan Verb',
  '捕る': 'Godan Verb',
  '暖まる': 'Godan Verb',
  '応ずる': 'Godan Verb',
  '打ち消す': 'Godan Verb',
  '承る': 'Godan Verb',
  '長引く': 'Godan Verb',
  '超す': 'Godan Verb',
  '掘る': 'Godan Verb',
  '怒鳴る': 'Godan Verb',
  '照らす': 'Godan Verb',
  '請う': 'Godan Verb',
  '取り出す': 'Godan Verb',
  '信ずる': 'Godan Verb',
  '実る': 'Godan Verb',
  '助かる': 'Godan Verb',
  '崩す': 'Godan Verb',
  '逃がす': 'Godan Verb',
  '訳す': 'Godan Verb',
  '縮む': 'Godan Verb',
  '命ずる': 'Godan Verb',
  '探る': 'Godan Verb',
  '縫う': 'Godan Verb',
  '映す': 'Godan Verb',
  '背負う': 'Godan Verb',
  '引っかかる': 'Godan Verb',
  '鳴らす': 'Godan Verb',
  '怠る': 'Godan Verb',
  '悔やむ': 'Godan Verb',
  '引き返す': 'Godan Verb',
  '濁る': 'Godan Verb',
  '飛び込む': 'Godan Verb',
  '出来上がる': 'Godan Verb',
  '裏返す': 'Godan Verb',
  '立ち止まる': 'Godan Verb',
  '誓う': 'Godan Verb',
  '付き合う': 'Godan Verb',
  '近寄る': 'Godan Verb',
  '見下ろす': 'Godan Verb',
  '透き通る': 'Godan Verb',
  '耕す': 'Godan Verb',
  '採る': 'Godan Verb',
  '嫌がる': 'Godan Verb',
  '教わる': 'Godan Verb',
  '重なる': 'Godan Verb',
  '固まる': 'Godan Verb',
  '受け持つ': 'Godan Verb',
  '言い出す': 'Godan Verb',
  '静まる': 'Godan Verb',
  '編む': 'Godan Verb',
  '偏る': 'Godan Verb',
  '担ぐ': 'Godan Verb',
  '当てはまる': 'Godan Verb',
  '彫る': 'Godan Verb',
  '反る': 'Godan Verb',
  '増やす': 'Godan Verb',
  '関わる': 'Godan Verb',
  '補う': 'Godan Verb',
  '澄む': 'Godan Verb',
  '汚す': 'Godan Verb',
  '張り切る': 'Godan Verb',
  '騙す': 'Godan Verb',
  '突き当たる': 'Godan Verb',
  '仕上がる': 'Godan Verb',
  '延ばす': 'Godan Verb',
  '注す': 'Godan Verb',
  '乾かす': 'Godan Verb',
  '区切る': 'Godan Verb',
  'ぶつかる': 'Godan Verb',
  'くっつく': 'Godan Verb',
  '巻く': 'Godan Verb',
  '生ずる': 'Godan Verb',
  '挟まる': 'Godan Verb',
  '響く': 'Godan Verb',
  'つまずく': 'Godan Verb',
  '刷る': 'Godan Verb',
  '帰す': 'Godan Verb',
  'しゃぶる': 'Godan Verb',
  'つく': 'Godan Verb',
  '追い越す': 'Godan Verb',
  '振る舞う': 'Godan Verb',
  '流行る': 'Godan Verb',
  'またぐ': 'Godan Verb',
  '敷く': 'Godan Verb',
  '片付く': 'Godan Verb',
  'ずらす': 'Godan Verb',
  '拝む': 'Godan Verb',
  'からかう': 'Godan Verb',
  '引っ込む': 'Godan Verb',
  'こぼす': 'Godan Verb',
  'ためらう': 'Godan Verb',
  '浮く': 'Godan Verb',
  '思い込む': 'Godan Verb',
  '冷ます': 'Godan Verb',
  '留まる': 'Godan Verb',
  '突く': 'Godan Verb',
  '測る': 'Godan Verb',
  '燃やす': 'Godan Verb',
  'ほどく': 'Godan Verb',
  '通ずる': 'Godan Verb',
  'つながる': 'Godan Verb',
  '散らす': 'Godan Verb',
  'しゃがむ': 'Godan Verb',
  '載る': 'Godan Verb',
  '甘やかす': 'Godan Verb',
  '憎む': 'Godan Verb',
  '思いつく': 'Godan Verb',
  'よこす': 'Godan Verb',
  '払い込む': 'Godan Verb',
  'おろす': 'Godan Verb',
  '揃う': 'Godan Verb',
  'あぶる': 'Godan Verb',
  '祭る': 'Godan Verb',
  '可愛がる': 'Godan Verb',
  '散らかる': 'Godan Verb',
  'どく': 'Godan Verb',
  'しぼむ': 'Godan Verb',
  '覗く': 'Godan Verb',
  '略す': 'Godan Verb',
  '傾く': 'Godan Verb',
  'ひっくり返す': 'Godan Verb',
  'なす': 'Godan Verb',
  '混ざる': 'Godan Verb',
  '威張る': 'Godan Verb',
  '儲かる': 'Godan Verb',
  'たまる': 'Godan Verb',
  '溶け込む': 'Godan Verb',
  '倣う': 'Godan Verb',
  '潰す': 'Godan Verb',
  '拭く': 'Godan Verb',
  '散らかす': 'Godan Verb',
  'すれ違う': 'Godan Verb',
  '落ち着く': 'Godan Verb',
  'わく': 'Godan Verb',
  '射す': 'Godan Verb',
  'よる': 'Godan Verb',
  '濡らす': 'Godan Verb',
  '潜る': 'Godan Verb',
  '焦がす': 'Godan Verb',
  '著す': 'Godan Verb',
  '敬う': 'Godan Verb',
  '跳ぶ': 'Godan Verb',
  '塞ぐ': 'Godan Verb',
  'たたむ': 'Godan Verb',
  '恨む': 'Godan Verb',
  '臭う': 'Godan Verb',
  'なくす': 'Godan Verb',
  '存ずる': 'Godan Verb',
  'むく': 'Godan Verb',
  '通りかかる': 'Godan Verb',
  '這う': 'Godan Verb',
  '裂く': 'Godan Verb',
  'こする': 'Godan Verb',
  '挿す': 'Godan Verb',
  '釣合う': 'Godan Verb',
  'もむ': 'Godan Verb',
  'つる': 'Godan Verb',
  '払戻す': 'Godan Verb',
  '破く': 'Godan Verb',
  '囁く': 'Godan Verb',
  '塞がる': 'Godan Verb',
  '炊く': 'Godan Verb',
  '吊す': 'Godan Verb',
  '睨む': 'Godan Verb',
  '砕く': 'Godan Verb',
  'かく': 'Godan Verb',
  'へこむ': 'Godan Verb',
  '嗅ぐ': 'Godan Verb',
  'さかのぼる': 'Godan Verb',
  'まく': 'Godan Verb',
  '剃る': 'Godan Verb',
  '溶く': 'Godan Verb',
  '羨む': 'Godan Verb',
  '渇く': 'Godan Verb',
  '汲む': 'Godan Verb',
  '引っ繰り返る': 'Godan Verb',
  '掃く': 'Godan Verb',
  '涼む': 'Godan Verb',
  '焚く': 'Godan Verb',
  '蒔く': 'Godan Verb',
  '尖る': 'Godan Verb',
  '剥がす': 'Godan Verb',
  '扇ぐ': 'Godan Verb',
  '纏まる': 'Godan Verb',
  '酌む': 'Godan Verb',
  '苛立つ': 'Godan Verb',
  '憐れむ': 'Godan Verb',
  '慈しむ': 'Godan Verb',
  '際立つ': 'Godan Verb',
  '促す': 'Godan Verb',
  '携わる': 'Godan Verb',
  '賄う': 'Godan Verb',
  '費やす': 'Godan Verb',
  '損なう': 'Godan Verb',
  '阻む': 'Godan Verb',
  '挑む': 'Godan Verb',
  '謀る': 'Godan Verb',
  '企む': 'Godan Verb',
  '欺く': 'Godan Verb',
  '偽る': 'Godan Verb',
  '装う': 'Godan Verb',
  '誇る': 'Godan Verb',
  '見込む': 'Godan Verb',
  '見計らう': 'Godan Verb',
  '見合う': 'Godan Verb',
  '適う': 'Godan Verb',
  '食い違う': 'Godan Verb',
  '逸らす': 'Godan Verb',
  '潤う': 'Godan Verb',
  '見逃す': 'Godan Verb',
  '目に余る': 'Godan Verb',
  '見過ごす': 'Godan Verb',
  '見落とす': 'Godan Verb',
  '見なす': 'Godan Verb',
  '仰ぐ': 'Godan Verb',
  '明かす': 'Godan Verb',
  '赤らむ': 'Godan Verb',
  'あざ笑う': 'Godan Verb',
  '炙る': 'Godan Verb',
  '操る': 'Godan Verb',
  '危ぶむ': 'Godan Verb',
  '誤る': 'Godan Verb',
  '歩む': 'Godan Verb',
  '荒らす': 'Godan Verb',
  '改まる': 'Godan Verb',
  '合わす': 'Godan Verb',
  '生かす': 'Godan Verb',
  '歪む': 'Godan Verb',
  '意気込む': 'Godan Verb',
  '痛む': 'Godan Verb',
  '労る': 'Godan Verb',
  '営む': 'Godan Verb',
  '受かる': 'Godan Verb',
  '受け継ぐ': 'Godan Verb',
  '埋まる': 'Godan Verb',
  '打ち切る': 'Godan Verb',
  '打ち込む': 'Godan Verb',
  '産む': 'Godan Verb',
  '埋め込む': 'Godan Verb',
  '売り出す': 'Godan Verb',
  '上回る': 'Godan Verb',
  '植わる': 'Godan Verb',
  '演ずる': 'Godan Verb',
  '追い込む': 'Godan Verb',
  '追い出す': 'Godan Verb',
  'お出でになる': 'Godan Verb',
  '負う': 'Godan Verb',
  '犯す': 'Godan Verb',
  '侵す': 'Godan Verb',
  '遅らす': 'Godan Verb',
  '傲る': 'Godan Verb',
  '収まる': 'Godan Verb',
  '納まる': 'Godan Verb',
  '治まる': 'Godan Verb',
  '押し込む': 'Godan Verb',
  '惜しむ': 'Godan Verb',
  '襲う': 'Godan Verb',
  '恐れ入る': 'Godan Verb',
  '落ち込む': 'Godan Verb',
  '仰っしゃる': 'Godan Verb',
  '脅かす': 'Godan Verb',
  '脅す': 'Godan Verb',
  '赴く': 'Godan Verb',
  '重んずる': 'Godan Verb',
  '及ぶ': 'Godan Verb',
  '折り返す': 'Godan Verb',
  '織る': 'Godan Verb',
  '返る': 'Godan Verb',
  '書き取る': 'Godan Verb',
  '掻き回す': 'Godan Verb',
  '欠く': 'Godan Verb',
  '嵩張る': 'Godan Verb',
  '嵩む': 'Godan Verb',
  '霞む': 'Godan Verb',
  '擦る': 'Godan Verb',
  '叶う': 'Godan Verb',
  '噛み切る': 'Godan Verb',
  '揶揄う': 'Godan Verb',
  '絡む': 'Godan Verb',
  '交わす': 'Godan Verb',
  '着飾る': 'Godan Verb',
  '軋む': 'Godan Verb',
  '築く': 'Godan Verb',
  '傷付く': 'Godan Verb',
  '禁ずる': 'Godan Verb',
  '口ずさむ': 'Godan Verb',
  'くっ付く': 'Godan Verb',
  '覆す': 'Godan Verb',
  '組み込む': 'Godan Verb',
  '蹴飛ばす': 'Godan Verb',
  '貶す': 'Godan Verb',
  '煙る': 'Godan Verb',
  '漕ぐ': 'Godan Verb',
  '志す': 'Godan Verb',
  '凝らす': 'Godan Verb',
  '凝る': 'Godan Verb',
  'こだわる': 'Godan Verb',
  '零す': 'Godan Verb',
  '混む': 'Godan Verb',
  '篭る': 'Godan Verb',
  'ご座います': 'Godan Verb',
  '誤魔化す': 'Godan Verb',
  '囀る': 'Godan Verb',
  '逆上る': 'Godan Verb',
  '差し掛かる': 'Godan Verb',
  '差し出す': 'Godan Verb',
  '差し引く': 'Godan Verb',
  '定まる': 'Godan Verb',
  '悟る': 'Godan Verb',
  '裁く': 'Godan Verb',
  '拐う': 'Godan Verb',
  '障る': 'Godan Verb',
  '仕切る': 'Godan Verb',
  '慕う': 'Godan Verb',
  '親しむ': 'Godan Verb',
  '凌ぐ': 'Godan Verb',
  '萎む': 'Godan Verb',
  '仕舞う': 'Godan Verb',
  '退く': 'Godan Verb',
  '記す': 'Godan Verb',
  '準ずる': 'Godan Verb',
  '掬う': 'Godan Verb',
  '濯ぐ': 'Godan Verb',
  '済ます': 'Godan Verb',
  '澄ます': 'Godan Verb',
  '急かす': 'Godan Verb',
  '沿う': 'Godan Verb',
  '添う': 'Godan Verb',
  '備わる': 'Godan Verb',
  '染まる': 'Godan Verb',
  '背く': 'Godan Verb',
  '高まる': 'Godan Verb',
  '漂う': 'Godan Verb',
  '立ち寄る': 'Godan Verb',
  '尊ぶ': 'Godan Verb',
  '絶つ': 'Godan Verb',
  '奉る': 'Godan Verb',
  '辿り着く': 'Godan Verb',
  '辿る': 'Godan Verb',
  '給う': 'Godan Verb',
  '賜る': 'Godan Verb',
  '躊躇う': 'Godan Verb',
  '保つ': 'Godan Verb',
  '弛む': 'Godan Verb',
  '近付く': 'Godan Verb',
  '縮まる': 'Godan Verb',
  '司る': 'Godan Verb',
  '尽くす': 'Godan Verb',
  '繕う': 'Godan Verb',
  '接ぐ': 'Godan Verb',
  '継ぐ': 'Godan Verb',
  '突っ張る': 'Godan Verb',
  '慎む': 'Godan Verb',
  '勤まる': 'Godan Verb',
  '募る': 'Godan Verb',
  '呟く': 'Godan Verb',
  '瞑る': 'Godan Verb',
  '躓く': 'Godan Verb',
  '摘む': 'Godan Verb',
  '強まる': 'Godan Verb',
  '連なる': 'Godan Verb',
  '貫く': 'Godan Verb',
  '吊るす': 'Godan Verb',
  '照り返す': 'Godan Verb',
  '出合う': 'Godan Verb',
  '出くわす': 'Godan Verb',
  '問う': 'Godan Verb',
  '遠ざかる': 'Godan Verb',
  '説く': 'Godan Verb',
  '研ぐ': 'Godan Verb',
  '滞る': 'Godan Verb',
  '富む': 'Godan Verb',
  '伴う': 'Godan Verb',
  '取り扱う': 'Godan Verb',
  '取り組む': 'Godan Verb',
  '取り締まる': 'Godan Verb',
  '取り次ぐ': 'Godan Verb',
  '取り除く': 'Godan Verb',
  '取り巻く': 'Godan Verb',
  '取り戻す': 'Godan Verb',
  '嘆く': 'Godan Verb',
  '投げ出す': 'Godan Verb',
  '為さる': 'Godan Verb',
  '懐く': 'Godan Verb',
  '鈍る': 'Godan Verb',
  '悩ます': 'Godan Verb',
  '慣らす': 'Godan Verb',
  '馴らす': 'Godan Verb',
  '成り立つ': 'Godan Verb',
  '似通う': 'Godan Verb',
  '賑わう': 'Godan Verb',
  '逃げ出す': 'Godan Verb',
  '滲む': 'Godan Verb',
  '担う': 'Godan Verb',
  '抜かす': 'Godan Verb',
  '抜け出す': 'Godan Verb',
  '妬む': 'Godan Verb',
  '強請る': 'Godan Verb',
  '粘る': 'Godan Verb',
  '逃す': 'Godan Verb',
  '臨む': 'Godan Verb',
  '乗っ取る': 'Godan Verb',
  '飲み込む': 'Godan Verb',
  '乗り込む': 'Godan Verb',
  '捗る': 'Godan Verb',
  '諮る': 'Godan Verb',
  '図る': 'Godan Verb',
  '剥ぐ': 'Godan Verb',
  '励ます': 'Godan Verb',
  '励む': 'Godan Verb',
  '恥じらう': 'Godan Verb',
  '弾む': 'Godan Verb',
  '果たす': 'Godan Verb',
  '填まる': 'Godan Verb',
  '生やす': 'Godan Verb',
  '散蒔く': 'Godan Verb',
  '引き起こす': 'Godan Verb',
  '引きずる': 'Godan Verb',
  '引き取る': 'Godan Verb',
  '浸す': 'Godan Verb',
  '引っ掻く': 'Godan Verb',
  '冷やかす': 'Godan Verb',
  '広まる': 'Godan Verb',
  '隔たる': 'Godan Verb',
  '謙る': 'Godan Verb',
  '報ずる': 'Godan Verb',
  '葬る': 'Godan Verb',
  '放り込む': 'Godan Verb',
  '放り出す': 'Godan Verb',
  '施す': 'Godan Verb',
  '滅ぼす': 'Godan Verb',
  'ぼやく': 'Godan Verb',
  '舞う': 'Godan Verb',
  '任す': 'Godan Verb',
  '負かす': 'Godan Verb',
  '捲る': 'Godan Verb',
  'まごつく': 'Godan Verb',
  '勝る': 'Godan Verb',
  '交わる': 'Godan Verb',
  '跨がる': 'Godan Verb',
  '跨ぐ': 'Godan Verb',
  '間違う': 'Godan Verb',
  '待ち望む': 'Godan Verb',
  '見せびらかす': 'Godan Verb',
  '満たす': 'Godan Verb',
  '乱す': 'Godan Verb',
  '導く': 'Godan Verb',
  '見渡す': 'Godan Verb',
  '結び付く': 'Godan Verb',
  '群がる': 'Godan Verb',
  '恵む': 'Godan Verb',
  '召す': 'Godan Verb',
  '藻掻く': 'Godan Verb',
  '齎らす': 'Godan Verb',
  '持て成す': 'Godan Verb',
  '催す': 'Godan Verb',
  '漏らす': 'Godan Verb',
  '盛り上がる': 'Godan Verb',
  '漏る': 'Godan Verb',
  '役立つ': 'Godan Verb',
  '養う': 'Godan Verb',
  '病む': 'Godan Verb',
  '遣り通す': 'Godan Verb',
  '遣る': 'Godan Verb',
  '揺さぶる': 'Godan Verb',
  '指差す': 'Godan Verb',
  '揺らぐ': 'Godan Verb',
  '緩む': 'Godan Verb',
  '寄こす': 'Godan Verb',
  '寄り掛かる': 'Godan Verb',
  '弱まる': 'Godan Verb',
  '弱る': 'Godan Verb',
  '割り込む': 'Godan Verb',
  'サボる': 'Godan Verb',
  'ダブる': 'Godan Verb',
  'お飲みになる': 'Godan Verb',
  'ご存知です': 'Godan Verb',
  'お話になる': 'Godan Verb',
  'お聞きになる': 'Godan Verb',
  'お電話をおかけになる': 'Godan Verb',
  'お会いになる': 'Godan Verb',
  'おもらいになる': 'Godan Verb',
  'おあげになる': 'Godan Verb',
  'お目にかかる': 'Godan Verb',
  'いただく': 'Godan Verb',
  'いたす': 'Godan Verb',
  '存じておる': 'Godan Verb',
  '居らっしゃる': 'Godan Verb',
  'お世話になる': 'Godan Verb',
  '擽る': 'Godan Verb',
  'くたばる': 'Godan Verb',
  '拘る': 'Godan Verb',
  'ことが出来る': 'Godan Verb',
  '事になる': 'Godan Verb',
  'せがむ': 'Godan Verb',
  'によって異なる': 'Godan Verb',
  '蔓延る': 'Godan Verb',
  'バテる': 'Godan Verb',
  'ぶら下がる': 'Godan Verb',
  'めく': 'Godan Verb',
  '様になる': 'Godan Verb',
  '寄越す': 'Godan Verb',
  '蹌踉めく': 'Godan Verb',
  'わくわく': 'Godan Verb',
  '哀れむ': 'Godan Verb',
  '握らす': 'Godan Verb',
  '圧倒': 'Godan Verb',
  '囲う': 'Godan Verb',
  '成す': 'Godan Verb',
  '依る': 'Godan Verb',
  '引き継ぐ': 'Godan Verb',
  '引き締まる': 'Godan Verb',
  '引き抜く': 'Godan Verb',
  '引き戻す': 'Godan Verb',
  '引き離す': 'Godan Verb',
  '引き裂く': 'Godan Verb',
  'ひっくり返る': 'Godan Verb',
  '詠む': 'Godan Verb',
  '凹む': 'Godan Verb',
  '押し切る': 'Godan Verb',
  '押し入る': 'Godan Verb',
  '横たわる': 'Godan Verb',
  '卸す': 'Godan Verb',
  '下さる': 'Godan Verb',
  '下す': 'Godan Verb',
  '嫁ぐ': 'Godan Verb',
  '怪しむ': 'Godan Verb',
  '懐かしむ': 'Godan Verb',
  '開き直る': 'Godan Verb',
  '割り引く': 'Godan Verb',
  '割り出す': 'Godan Verb',
  '割り切る': 'Godan Verb',
  '括る': 'Godan Verb',
  '噛み付く': 'Godan Verb',
  '刈り込む': 'Godan Verb',
  '刈り取る': 'Godan Verb',
  '巻き込む': 'Godan Verb',
  '喚く': 'Godan Verb',
  '寛ぐ': 'Godan Verb',
  '患う': 'Godan Verb',
  '感じ取る': 'Godan Verb',
  '貫き通す': 'Godan Verb',
  '丸め込む': 'Godan Verb',
  '頑張る': 'Godan Verb',
  '顔を潰す': 'Godan Verb',
  '寄り集まる': 'Godan Verb',
  '気取る': 'Godan Verb',
  '起き上がる': 'Godan Verb',
  '吃る': 'Godan Verb',
  '詰む': 'Godan Verb',
  '詰め込む': 'Godan Verb',
  '休まる': 'Godan Verb',
  '吸い込む': 'Godan Verb',
  '汲み取る': 'Godan Verb',
  '拒む': 'Godan Verb',
  '漁る': 'Godan Verb',
  '競う': 'Godan Verb',
  '狭まる': 'Godan Verb',
  '興す': 'Godan Verb',
  '仰る': 'Godan Verb',
  '近づく': 'Godan Verb',
  '駆け回る': 'Godan Verb',
  '駆る': 'Godan Verb',
  '繰り出す': 'Godan Verb',
  '繰る': 'Godan Verb',
  '憩う': 'Godan Verb',
  '繋がる': 'Godan Verb',
  '迎え撃つ': 'Godan Verb',
  '欠かす': 'Godan Verb',
  '結う': 'Godan Verb',
  '結びつく': 'Godan Verb',
  '見出す': 'Godan Verb',
  '見下す': 'Godan Verb',
  '見失う': 'Godan Verb',
  '見守る': 'Godan Verb',
  '見習う': 'Godan Verb',
  '見晴らす': 'Godan Verb',
  '見損なう': 'Godan Verb',
  '見張る': 'Godan Verb',
  '見当たる': 'Godan Verb',
  '見返す': 'Godan Verb',
  '言い切る': 'Godan Verb',
  '言い渡す': 'Godan Verb',
  '言い表す': 'Godan Verb',
  '言い返す': 'Godan Verb',
  '呼び戻す': 'Godan Verb',
  '戸惑う': 'Godan Verb',
  '語らう': 'Godan Verb',
  '光り輝く': 'Godan Verb',
  '口走る': 'Godan Verb',
  '口ごもる': 'Godan Verb',
  '考え直す': 'Godan Verb',
  '行き届く': 'Godan Verb',
  '根ざす': 'Godan Verb',
  '唆す': 'Godan Verb',
  '差し込む': 'Godan Verb',
  '差し戻す': 'Godan Verb',
  '彩る': 'Godan Verb',
  '細る': 'Godan Verb',
  '裁つ': 'Godan Verb',
  '有る': 'Godan Verb',
  '作り出す': 'Godan Verb',
  '撒く': 'Godan Verb',
  '散らばる': 'Godan Verb',
  '刺し殺す': 'Godan Verb',
  '思いとどまる': 'Godan Verb',
  '思い上がる': 'Godan Verb',
  '思い切る': 'Godan Verb',
  '思い直す': 'Godan Verb',
  '思い当たる': 'Godan Verb',
  '指し示す': 'Godan Verb',
  '上手く行く': 'Godan Verb',
  '止す': 'Godan Verb',
  '持ち越す': 'Godan Verb',
  '持ち込む': 'Godan Verb',
  '持ち出す': 'Godan Verb',
  '持ち直す': 'Godan Verb',
  '持っていく': 'Godan Verb',
  '偲ぶ': 'Godan Verb',
  '煮やす': 'Godan Verb',
  '煮込む': 'Godan Verb',
  '取り囲む': 'Godan Verb',
  '取り外す': 'Godan Verb',
  '取り掛かる': 'Godan Verb',
  '取り込む': 'Godan Verb',
  '取り残す': 'Godan Verb',
  '取り返す': 'Godan Verb',
  '手に入る': 'Godan Verb',
  '手渡す': 'Godan Verb',
  '呪う': 'Godan Verb',
  '授かる': 'Godan Verb',
  '集う': 'Godan Verb',
  '集る': 'Godan Verb',
  '住まう': 'Godan Verb',
  '渋る': 'Godan Verb',
  '重る': 'Godan Verb',
  '宿す': 'Godan Verb',
  '宿る': 'Godan Verb',
  '出向く': 'Godan Verb',
  '出来る': 'Godan Verb',
  '瞬く': 'Godan Verb',
  '潤す': 'Godan Verb',
  '潤む': 'Godan Verb',
  'めぐり合う': 'Godan Verb',
  '書き込む': 'Godan Verb',
  '書き直す': 'Godan Verb',
  '助け合う': 'Godan Verb',
  '償う': 'Godan Verb',
  '上る': 'Godan Verb',
  '乗ずる': 'Godan Verb',
  '乗り越す': 'Godan Verb',
  '乗り回す': 'Godan Verb',
  '乗り出す': 'Godan Verb',
  '乗り切る': 'Godan Verb',
  '畳む': 'Godan Verb',
  '蒸かす': 'Godan Verb',
  '蒸し返す': 'Godan Verb',
  '譲り渡す': 'Godan Verb',
  '拭う': 'Godan Verb',
  '触れ合う': 'Godan Verb',
  '食い込む': 'Godan Verb',
  '蝕む': 'Godan Verb',
  '伸び悩む': 'Godan Verb',
  '寝かす': 'Godan Verb',
  '寝付く': 'Godan Verb',
  '寝返る': 'Godan Verb',
  '振り回す': 'Godan Verb',
  '振り向く': 'Godan Verb',
  '振り込む': 'Godan Verb',
  '振り切る': 'Godan Verb',
  '振り返る': 'Godan Verb',
  '浸る': 'Godan Verb',
  '吹き込む': 'Godan Verb',
  '吹き飛ぶ': 'Godan Verb',
  '垂らす': 'Godan Verb',
  '推す': 'Godan Verb',
  '酔っ払う': 'Godan Verb',
  '澄み切る': 'Godan Verb',
  '晴らす': 'Godan Verb',
  '正す': 'Godan Verb',
  '生き残る': 'Godan Verb',
  '生き返る': 'Godan Verb',
  '生み出す': 'Godan Verb',
  '盛り込む': 'Godan Verb',
  '請け負う': 'Godan Verb',
  '積み込む': 'Godan Verb',
  '切らす': 'Godan Verb',
  '切り崩す': 'Godan Verb',
  '切り離す': 'Godan Verb',
  '絶やす': 'Godan Verb',
  '潜む': 'Godan Verb',
  '煽る': 'Godan Verb',
  '閃く': 'Godan Verb',
  '遡る': 'Godan Verb',
  '掻く': 'Godan Verb',
  '早まる': 'Godan Verb',
  '燥ぐ': 'Godan Verb',
  '相次ぐ': 'Godan Verb',
  '走り回る': 'Godan Verb',
  '走り出す': 'Godan Verb',
  '送り込む': 'Godan Verb',
  '送り返す': 'Godan Verb',
  '騒めく': 'Godan Verb',
  '打ち出す': 'Godan Verb',
  '貸し出す': 'Godan Verb',
  '濁す': 'Godan Verb',
  'たどり着く': 'Godan Verb',
  '耽る': 'Godan Verb',
  '値切る': 'Godan Verb',
  '知り合う': 'Godan Verb',
  '張り出す': 'Godan Verb',
  '飛び上がる': 'Godan Verb',
  '追い抜く': 'Godan Verb',
  '浸かる': 'Godan Verb',
  '綴る': 'Godan Verb',
  '吊る': 'Godan Verb',
  '釣り合う': 'Godan Verb',
  '点く': 'Godan Verb',
  '伝う': 'Godan Verb',
  '吐き出す': 'Godan Verb',
  '悼む': 'Godan Verb',
  '投げ込む': 'Godan Verb',
  '踏み切る': 'Godan Verb',
  '踏ん張る': 'Godan Verb',
  '読み返す': 'Godan Verb',
  '突き刺す': 'Godan Verb',
  '突っ込む': 'Godan Verb',
  '馴染む': 'Godan Verb',
  '入り込む': 'Godan Verb',
  '忍ぶ': 'Godan Verb',
  '年をとる': 'Godan Verb',
  '燃え上がる': 'Godan Verb',
  '培う': 'Godan Verb',
  '売り込む': 'Godan Verb',
  '剥く': 'Godan Verb',
  '薄らぐ': 'Godan Verb',
  '抜かる': 'Godan Verb',
  '庇う': 'Godan Verb',
  '飛び交う': 'Godan Verb',
  '表立つ': 'Godan Verb',
  'ついて行く': 'Godan Verb',
  'つけ込む': 'Godan Verb',
  '付け足す': 'Godan Verb',
  '怖がる': 'Godan Verb',
  '浮かび上がる': 'Godan Verb',
  '風邪をひく': 'Godan Verb',
  '払い戻す': 'Godan Verb',
  '分かつ': 'Godan Verb',
  '奮う': 'Godan Verb',
  '紛らす': 'Godan Verb',
  '聞かす': 'Godan Verb',
  '聞き取る': 'Godan Verb',
  '閉ざす': 'Godan Verb',
  '閉じこもる': 'Godan Verb',
  '僻む': 'Godan Verb',
  '蔑む': 'Godan Verb',
  '歩き回る': 'Godan Verb',
  '歩み寄る': 'Godan Verb',
  '包み込む': 'Godan Verb',
  '抱き合う': 'Godan Verb',
  '放つ': 'Godan Verb',
  '冒す': 'Godan Verb',
  '紡ぐ': 'Godan Verb',
  '翻す': 'Godan Verb',
  '摩る': 'Godan Verb',
  '名乗る': 'Godan Verb',
  '迷う': 'Godan Verb',
  '目を通す': 'Godan Verb',
  '諭す': 'Godan Verb',
  '勇む': 'Godan Verb',
  '余す': 'Godan Verb',
  '揺るぐ': 'Godan Verb',
  '欲張る': 'Godan Verb',
  '頼む': 'Godan Verb',
  '絡み合う': 'Godan Verb',
  '落ち合う': 'Godan Verb',
  '立ち去る': 'Godan Verb',
  '立ち退く': 'Godan Verb',
  '立ち直る': 'Godan Verb',
  '流れ込む': 'Godan Verb',
  '溜まる': 'Godan Verb',
  '旅立つ': 'Godan Verb',
  '力む': 'Godan Verb',
  '冷え込む': 'Godan Verb',
  '連れ去る': 'Godan Verb',
  '論じ尽くす': 'Godan Verb',
  '和む': 'Godan Verb',
  '和らぐ': 'Godan Verb',
  '話し込む': 'Godan Verb',
  '惑わす': 'Godan Verb',
  '捥ぐ': 'Godan Verb',
  '仄めかす': 'Godan Verb',
  '佇む': 'Godan Verb',
  '俯く': 'Godan Verb',
  '奢る': 'Godan Verb',
  '彷徨う': 'Godan Verb',
  '彷徨く': 'Godan Verb',
  '揉む': 'Godan Verb',
  '暈す': 'Godan Verb',
  '貪る': 'Godan Verb',
  '齎す': 'Godan Verb',
  '跪く': 'Godan Verb',
  '蹲る': 'Godan Verb',
  '頷く': 'Godan Verb',
  '靡く': 'Godan Verb',
  '注ぎ込む': 'Godan Verb',
  'つぎ込む': 'Godan Verb',
  '弔う': 'Godan Verb',
  '灯す': 'Godan Verb',
  '侮る': 'Godan Verb',
  '揺る': 'Godan Verb',
  '温まる': 'Godan Verb',
  '行き渡る': 'Godan Verb',
  '生む': 'Godan Verb',
  '香る': 'Godan Verb',
  '替わる': 'Godan Verb',
  '気がつく': 'Godan Verb',
  '傷つく': 'Godan Verb',
  '極まる': 'Godan Verb',
  '食らう': 'Godan Verb',
  '乞う': 'Godan Verb',
  '恋う': 'Godan Verb',
  '籠もる': 'Godan Verb',
  '肥やす': 'Godan Verb',
  '探し回る': 'Godan Verb',
  '浚う': 'Godan Verb',
  '晒す': 'Godan Verb',
  '締め出す': 'Godan Verb',
  '断つ': 'Godan Verb',
  '立て込む': 'Godan Verb',
  '連れて行く': 'Godan Verb',
  '梳かす': 'Godan Verb',
  '隣り合う': 'Godan Verb',
  '執る': 'Godan Verb',
  '匂う': 'Godan Verb',
  '寝転ぶ': 'Godan Verb',
  '育む': 'Godan Verb',
  '跳ね上がる': 'Godan Verb',
  '嵌まる': 'Godan Verb',
  'はみ出す': 'Godan Verb',
  '歯向かう': 'Godan Verb',
  'ばら撒く': 'Godan Verb',
  '引きつる': 'Godan Verb',
  '引き伸ばす': 'Godan Verb',
  '引き渡す': 'Godan Verb',
  '吹き出す': 'Godan Verb',
  '振舞う': 'Godan Verb',
  '跨る': 'Godan Verb',
  '見破る': 'Godan Verb',
  'やり直す': 'Godan Verb',
  '分かる': 'Godan Verb',
  '湧く': 'Godan Verb',
  '映し出す': 'Godan Verb',
  '見放す': 'Godan Verb',
  '薄まる': 'Godan Verb',
  '謳う': 'Godan Verb',
  '食い下がる': 'Godan Verb',
  '縋る': 'Godan Verb',
  '託す': 'Godan Verb',
  '糺す': 'Godan Verb',
  '楯突く': 'Godan Verb',
  '立て直す': 'Godan Verb',
  '寝過ごす': 'Godan Verb',
  '孕む': 'Godan Verb',
  '引っ付く': 'Godan Verb',
  '欲しがる': 'Godan Verb',
  '見限る': 'Godan Verb',
  '揺るがす': 'Godan Verb',
  '喜ばす': 'Godan Verb',
  '淀む': 'Godan Verb',
  '御座います': 'Godan Verb',
  'やり過ごす': 'Godan Verb',
  '熟す': 'Godan Verb',
  '響めく': 'Godan Verb',
  '安らぐ': 'Godan Verb',
  '競り合う': 'Godan Verb',
  '講ずる': 'Godan Verb',
  '擤む': 'Godan Verb',
  '全うする': 'Godan Verb',
  '思い描く': 'Godan Verb',
  '勝ち越す': 'Godan Verb',
  '混ぜ合わす': 'Godan Verb',
  '思い起こす': 'Godan Verb',
  '持ち帰る': 'Godan Verb',
  '見入る': 'Godan Verb',
  '相手取る': 'Godan Verb',
  '怒鳴り込む': 'Godan Verb',
  '逃げ切る': 'Godan Verb',
  '思いやる': 'Godan Verb',
  '棲む': 'Godan Verb',
  'ばらす': 'Godan Verb',
  '絞り込む': 'Godan Verb',
  '待たす': 'Godan Verb',
  '解きほぐす': 'Godan Verb',
  '動き出す': 'Godan Verb',
  'ちゃう': 'Godan Verb',
  '摂る': 'Godan Verb',
  '丸まる': 'Godan Verb',
  'でもある': 'Godan Verb',
  'となる': 'Godan Verb',
  '顔を出す': 'Godan Verb',
  '責任を持つ': 'Godan Verb',
  'とく': 'Godan Verb',
  '何を隠そう': 'Godan Verb',
  'たがる': 'Godan Verb',
  '生まれ育つ': 'Godan Verb',
  '一味違う': 'Godan Verb',
  '絵を描く': 'Godan Verb',
  '愛す': 'Godan Verb',
  '辞す': 'Godan Verb',
  '亡くす': 'Godan Verb',
  '大人になる': 'Godan Verb',
  '大きくなる': 'Godan Verb',
  '訊く': 'Godan Verb',
  '雨が降る': 'Godan Verb',
  '驕る': 'Godan Verb',
  '為す': 'Godan Verb',
  '煩う': 'Godan Verb',
  '出る': 'Ichidan Verb',
  '考える': 'Ichidan Verb',
  '食べる': 'Ichidan Verb',
  '入れる': 'Ichidan Verb',
  '始める': 'Ichidan Verb',
  '感じる': 'Ichidan Verb',
  '教える': 'Ichidan Verb',
  '覚える': 'Ichidan Verb',
  '見る': 'Ichidan Verb',
  '浴びる': 'Ichidan Verb',
  '着る': 'Ichidan Verb',
  'かける': 'Ichidan Verb',
  '寝る': 'Ichidan Verb',
  '降りる': 'Ichidan Verb',
  '借りる': 'Ichidan Verb',
  '出かける': 'Ichidan Verb',
  '締める': 'Ichidan Verb',
  '見せる': 'Ichidan Verb',
  '起きる': 'Ichidan Verb',
  '閉める': 'Ichidan Verb',
  '晴れる': 'Ichidan Verb',
  '答える': 'Ichidan Verb',
  '上げる': 'Ichidan Verb',
  '疲れる': 'Ichidan Verb',
  'つける': 'Ichidan Verb',
  '消える': 'Ichidan Verb',
  '生まれる': 'Ichidan Verb',
  '開ける': 'Ichidan Verb',
  '居る': 'Ichidan Verb',
  '忘れる': 'Ichidan Verb',
  '並べる': 'Ichidan Verb',
  '勤める': 'Ichidan Verb',
  '見える': 'Ichidan Verb',
  '生きる': 'Ichidan Verb',
  '比べる': 'Ichidan Verb',
  '受ける': 'Ichidan Verb',
  '下げる': 'Ichidan Verb',
  '集める': 'Ichidan Verb',
  '落ちる': 'Ichidan Verb',
  'くれる': 'Ichidan Verb',
  '訪ねる': 'Ichidan Verb',
  '下りる': 'Ichidan Verb',
  '倒れる': 'Ichidan Verb',
  '逃げる': 'Ichidan Verb',
  '決める': 'Ichidan Verb',
  '増える': 'Ichidan Verb',
  '暮れる': 'Ichidan Verb',
  '掛ける': 'Ichidan Verb',
  '申し上げる': 'Ichidan Verb',
  '迎える': 'Ichidan Verb',
  '聞こえる': 'Ichidan Verb',
  '別れる': 'Ichidan Verb',
  '変える': 'Ichidan Verb',
  '壊れる': 'Ichidan Verb',
  '漬ける': 'Ichidan Verb',
  '冷える': 'Ichidan Verb',
  '乗り換える': 'Ichidan Verb',
  '負ける': 'Ichidan Verb',
  '間違える': 'Ichidan Verb',
  '続ける': 'Ichidan Verb',
  '尋ねる': 'Ichidan Verb',
  '調べる': 'Ichidan Verb',
  '汚れる': 'Ichidan Verb',
  '似る': 'Ichidan Verb',
  '差し上げる': 'Ichidan Verb',
  '褒める': 'Ichidan Verb',
  '捕まえる': 'Ichidan Verb',
  '見つける': 'Ichidan Verb',
  '伝える': 'Ichidan Verb',
  '片付ける': 'Ichidan Verb',
  '遅れる': 'Ichidan Verb',
  '足りる': 'Ichidan Verb',
  '投げる': 'Ichidan Verb',
  '濡れる': 'Ichidan Verb',
  '立てる': 'Ichidan Verb',
  '育てる': 'Ichidan Verb',
  '止める': 'Ichidan Verb',
  '知らせる': 'Ichidan Verb',
  '慣れる': 'Ichidan Verb',
  '捨てる': 'Ichidan Verb',
  '建てる': 'Ichidan Verb',
  '揺れる': 'Ichidan Verb',
  'いじめる': 'Ichidan Verb',
  '植える': 'Ichidan Verb',
  '割れる': 'Ichidan Verb',
  '届ける': 'Ichidan Verb',
  '取り替える': 'Ichidan Verb',
  '焼ける': 'Ichidan Verb',
  '折れる': 'Ichidan Verb',
  '痩せる': 'Ichidan Verb',
  '閉じる': 'Ichidan Verb',
  '合わせる': 'Ichidan Verb',
  '分ける': 'Ichidan Verb',
  '離れる': 'Ichidan Verb',
  '終える': 'Ichidan Verb',
  '越える': 'Ichidan Verb',
  '応じる': 'Ichidan Verb',
  '当てる': 'Ichidan Verb',
  '抱える': 'Ichidan Verb',
  '備える': 'Ichidan Verb',
  '載せる': 'Ichidan Verb',
  '助ける': 'Ichidan Verb',
  '数える': 'Ichidan Verb',
  '恐れる': 'Ichidan Verb',
  '用いる': 'Ichidan Verb',
  '燃える': 'Ichidan Verb',
  '確かめる': 'Ichidan Verb',
  '加える': 'Ichidan Verb',
  '与える': 'Ichidan Verb',
  '収める': 'Ichidan Verb',
  '生じる': 'Ichidan Verb',
  '眺める': 'Ichidan Verb',
  '命じる': 'Ichidan Verb',
  '預ける': 'Ichidan Verb',
  '通り過ぎる': 'Ichidan Verb',
  '論じる': 'Ichidan Verb',
  '持ち上げる': 'Ichidan Verb',
  '満ちる': 'Ichidan Verb',
  '認める': 'Ichidan Verb',
  '飽きる': 'Ichidan Verb',
  '信じる': 'Ichidan Verb',
  '得る': 'Ichidan Verb',
  '辞める': 'Ichidan Verb',
  '求める': 'Ichidan Verb',
  '現れる': 'Ichidan Verb',
  '付ける': 'Ichidan Verb',
  '訴える': 'Ichidan Verb',
  '流れる': 'Ichidan Verb',
  '取り上げる': 'Ichidan Verb',
  '支える': 'Ichidan Verb',
  '覚める': 'Ichidan Verb',
  '取れる': 'Ichidan Verb',
  '通じる': 'Ichidan Verb',
  '切れる': 'Ichidan Verb',
  '進める': 'Ichidan Verb',
  '売れる': 'Ichidan Verb',
  '抜ける': 'Ichidan Verb',
  'しゃべる': 'Ichidan Verb',
  '触れる': 'Ichidan Verb',
  '向ける': 'Ichidan Verb',
  '優れる': 'Ichidan Verb',
  '伸びる': 'Ichidan Verb',
  '避ける': 'Ichidan Verb',
  '述べる': 'Ichidan Verb',
  '責める': 'Ichidan Verb',
  '明ける': 'Ichidan Verb',
  '解ける': 'Ichidan Verb',
  '任せる': 'Ichidan Verb',
  '済ませる': 'Ichidan Verb',
  '占める': 'Ichidan Verb',
  '隠れる': 'Ichidan Verb',
  '留める': 'Ichidan Verb',
  '震える': 'Ichidan Verb',
  '替える': 'Ichidan Verb',
  '欠ける': 'Ichidan Verb',
  '換える': 'Ichidan Verb',
  '勧める': 'Ichidan Verb',
  '諦める': 'Ichidan Verb',
  '溺れる': 'Ichidan Verb',
  '吠える': 'Ichidan Verb',
  '怠ける': 'Ichidan Verb',
  '言いつける': 'Ichidan Verb',
  'かじる': 'Ichidan Verb',
  '超える': 'Ichidan Verb',
  '高める': 'Ichidan Verb',
  '広げる': 'Ichidan Verb',
  '重ねる': 'Ichidan Verb',
  '押さえる': 'Ichidan Verb',
  '分かれる': 'Ichidan Verb',
  '努める': 'Ichidan Verb',
  '寄せる': 'Ichidan Verb',
  '攻める': 'Ichidan Verb',
  '改める': 'Ichidan Verb',
  '崩れる': 'Ichidan Verb',
  '咥える': 'Ichidan Verb',
  '耐える': 'Ichidan Verb',
  '埋める': 'Ichidan Verb',
  '慌てる': 'Ichidan Verb',
  '浮かべる': 'Ichidan Verb',
  '煮る': 'Ichidan Verb',
  '出迎える': 'Ichidan Verb',
  '外れる': 'Ichidan Verb',
  '納める': 'Ichidan Verb',
  '浸ける': 'Ichidan Verb',
  '暴れる': 'Ichidan Verb',
  '例える': 'Ichidan Verb',
  '診る': 'Ichidan Verb',
  '兼ねる': 'Ichidan Verb',
  '出掛ける': 'Ichidan Verb',
  '広める': 'Ichidan Verb',
  '冷める': 'Ichidan Verb',
  '枯れる': 'Ichidan Verb',
  '隔てる': 'Ichidan Verb',
  '殖える': 'Ichidan Verb',
  '着せる': 'Ichidan Verb',
  '捕らえる': 'Ichidan Verb',
  '焦げる': 'Ichidan Verb',
  '見慣れる': 'Ichidan Verb',
  '引き受ける': 'Ichidan Verb',
  '曲げる': 'Ichidan Verb',
  '飢える': 'Ichidan Verb',
  '存じる': 'Ichidan Verb',
  '挙げる': 'Ichidan Verb',
  'あふれる': 'Ichidan Verb',
  '混ぜる': 'Ichidan Verb',
  '薄める': 'Ichidan Verb',
  '腰掛ける': 'Ichidan Verb',
  '組み立てる': 'Ichidan Verb',
  '取り入れる': 'Ichidan Verb',
  '話しかける': 'Ichidan Verb',
  '点ける': 'Ichidan Verb',
  '泊める': 'Ichidan Verb',
  'こぼれる': 'Ichidan Verb',
  '気をつける': 'Ichidan Verb',
  '揚げる': 'Ichidan Verb',
  '着ける': 'Ichidan Verb',
  '務める': 'Ichidan Verb',
  '蓄える': 'Ichidan Verb',
  'ぶつける': 'Ichidan Verb',
  '放れる': 'Ichidan Verb',
  '生える': 'Ichidan Verb',
  '妨げる': 'Ichidan Verb',
  '斬る': 'Ichidan Verb',
  'ずれる': 'Ichidan Verb',
  '売切れる': 'Ichidan Verb',
  'はめる': 'Ichidan Verb',
  '跳ねる': 'Ichidan Verb',
  'ふざける': 'Ichidan Verb',
  'くっつける': 'Ichidan Verb',
  'しびれる': 'Ichidan Verb',
  '治める': 'Ichidan Verb',
  '呆れる': 'Ichidan Verb',
  '湯でる': 'Ichidan Verb',
  '含める': 'Ichidan Verb',
  '言付ける': 'Ichidan Verb',
  'やっつける': 'Ichidan Verb',
  'もたれる': 'Ichidan Verb',
  '待ち合わせる': 'Ichidan Verb',
  'ちぎる': 'Ichidan Verb',
  '代える': 'Ichidan Verb',
  '近づける': 'Ichidan Verb',
  '恵まれる': 'Ichidan Verb',
  '引き止める': 'Ichidan Verb',
  '破れる': 'Ichidan Verb',
  'かぶせる': 'Ichidan Verb',
  'こしらえる': 'Ichidan Verb',
  '揃える': 'Ichidan Verb',
  '縮める': 'Ichidan Verb',
  '真似る': 'Ichidan Verb',
  '当てはめる': 'Ichidan Verb',
  '溶ける': 'Ichidan Verb',
  'のける': 'Ichidan Verb',
  'くたびれる': 'Ichidan Verb',
  '温める': 'Ichidan Verb',
  '呼びかける': 'Ichidan Verb',
  'ぶら下げる': 'Ichidan Verb',
  '潰れる': 'Ichidan Verb',
  'つなげる': 'Ichidan Verb',
  '憧れる': 'Ichidan Verb',
  '儲ける': 'Ichidan Verb',
  '撫でる': 'Ichidan Verb',
  'なれる': 'Ichidan Verb',
  '慰める': 'Ichidan Verb',
  '溜める': 'Ichidan Verb',
  '追いかける': 'Ichidan Verb',
  '凍える': 'Ichidan Verb',
  'しめる': 'Ichidan Verb',
  '更ける': 'Ichidan Verb',
  '砕ける': 'Ichidan Verb',
  'まとめる': 'Ichidan Verb',
  '錆びる': 'Ichidan Verb',
  '逸れる': 'Ichidan Verb',
  '縮れる': 'Ichidan Verb',
  '煮える': 'Ichidan Verb',
  '詫びる': 'Ichidan Verb',
  '捩じる': 'Ichidan Verb',
  '遂げる': 'Ichidan Verb',
  '携える': 'Ichidan Verb',
  '遮る': 'Ichidan Verb',
  '企てる': 'Ichidan Verb',
  '講じる': 'Ichidan Verb',
  '踏まえる': 'Ichidan Verb',
  '見合わせる': 'Ichidan Verb',
  '見極める': 'Ichidan Verb',
  '見定める': 'Ichidan Verb',
  '見据える': 'Ichidan Verb',
  '大目に見る': 'Ichidan Verb',
  '転じる': 'Ichidan Verb',
  '見受ける': 'Ichidan Verb',
  '誂える': 'Ichidan Verb',
  '宛てる': 'Ichidan Verb',
  '溢れる': 'Ichidan Verb',
  '甘える': 'Ichidan Verb',
  '現われる': 'Ichidan Verb',
  '案じる': 'Ichidan Verb',
  '活ける': 'Ichidan Verb',
  '苛める': 'Ichidan Verb',
  '痛める': 'Ichidan Verb',
  '炒める': 'Ichidan Verb',
  '受け入れる': 'Ichidan Verb',
  '受け付ける': 'Ichidan Verb',
  '受け止める': 'Ichidan Verb',
  '打ち合わせる': 'Ichidan Verb',
  '演じる': 'Ichidan Verb',
  '老いる': 'Ichidan Verb',
  '押し寄せる': 'Ichidan Verb',
  '煽てる': 'Ichidan Verb',
  '訪れる': 'Ichidan Verb',
  '衰える': 'Ichidan Verb',
  '怯える': 'Ichidan Verb',
  '帯びる': 'Ichidan Verb',
  '重んじる': 'Ichidan Verb',
  '顧みる': 'Ichidan Verb',
  '省みる': 'Ichidan Verb',
  '掲げる': 'Ichidan Verb',
  '駆ける': 'Ichidan Verb',
  '賭ける': 'Ichidan Verb',
  '傾ける': 'Ichidan Verb',
  '固める': 'Ichidan Verb',
  '叶える': 'Ichidan Verb',
  '気触れる': 'Ichidan Verb',
  '構える': 'Ichidan Verb',
  '涸れる': 'Ichidan Verb',
  '鍛える': 'Ichidan Verb',
  '興じる': 'Ichidan Verb',
  '切り替える': 'Ichidan Verb',
  '禁じる': 'Ichidan Verb',
  '草臥れる': 'Ichidan Verb',
  '朽ちる': 'Ichidan Verb',
  'くっ付ける': 'Ichidan Verb',
  '組み合わせる': 'Ichidan Verb',
  '苦しめる': 'Ichidan Verb',
  '呉れる': 'Ichidan Verb',
  '心掛ける': 'Ichidan Verb',
  '試みる': 'Ichidan Verb',
  '拵える': 'Ichidan Verb',
  '拗れる': 'Ichidan Verb',
  '堪える': 'Ichidan Verb',
  '零れる': 'Ichidan Verb',
  '込める': 'Ichidan Verb',
  '懲りる': 'Ichidan Verb',
  '冴える': 'Ichidan Verb',
  '栄える': 'Ichidan Verb',
  '裂ける': 'Ichidan Verb',
  '捧げる': 'Ichidan Verb',
  '差し支える': 'Ichidan Verb',
  '授ける': 'Ichidan Verb',
  '定める': 'Ichidan Verb',
  '仕上げる': 'Ichidan Verb',
  '強いる': 'Ichidan Verb',
  '仕入れる': 'Ichidan Verb',
  '仕掛ける': 'Ichidan Verb',
  'しくじる': 'Ichidan Verb',
  '沈める': 'Ichidan Verb',
  '仕立てる': 'Ichidan Verb',
  '仕付ける': 'Ichidan Verb',
  '萎びる': 'Ichidan Verb',
  '痺れる': 'Ichidan Verb',
  '染みる': 'Ichidan Verb',
  '洒落る': 'Ichidan Verb',
  '退ける': 'Ichidan Verb',
  '準じる': 'Ichidan Verb',
  '据え付ける': 'Ichidan Verb',
  '据える': 'Ichidan Verb',
  '廃れる': 'Ichidan Verb',
  '擦れる': 'Ichidan Verb',
  '添える': 'Ichidan Verb',
  '備え付ける': 'Ichidan Verb',
  '聳える': 'Ichidan Verb',
  '染める': 'Ichidan Verb',
  '絶える': 'Ichidan Verb',
  '垂れる': 'Ichidan Verb',
  '違える': 'Ichidan Verb',
  '契る': 'Ichidan Verb',
  '仕える': 'Ichidan Verb',
  '尽きる': 'Ichidan Verb',
  '付け加える': 'Ichidan Verb',
  '告げる': 'Ichidan Verb',
  '強める': 'Ichidan Verb',
  '連ねる': 'Ichidan Verb',
  '手掛ける': 'Ichidan Verb',
  '問い合わせる': 'Ichidan Verb',
  '咎める': 'Ichidan Verb',
  '跡切れる': 'Ichidan Verb',
  '綴じる': 'Ichidan Verb',
  '途絶える': 'Ichidan Verb',
  '整える': 'Ichidan Verb',
  '唱える': 'Ichidan Verb',
  '取り調べる': 'Ichidan Verb',
  '取り立てる': 'Ichidan Verb',
  '取り混ぜる': 'Ichidan Verb',
  '取り寄せる': 'Ichidan Verb',
  '蕩ける': 'Ichidan Verb',
  '名付ける': 'Ichidan Verb',
  '嘗める': 'Ichidan Verb',
  '寝かせる': 'Ichidan Verb',
  '捻じれる': 'Ichidan Verb',
  '逃れる': 'Ichidan Verb',
  '映える': 'Ichidan Verb',
  '剥げる': 'Ichidan Verb',
  '恥じる': 'Ichidan Verb',
  '果てる': 'Ichidan Verb',
  '填める': 'Ichidan Verb',
  '早める': 'Ichidan Verb',
  '腫れる': 'Ichidan Verb',
  '化ける': 'Ichidan Verb',
  'ばてる': 'Ichidan Verb',
  '控える': 'Ichidan Verb',
  '引き上げる': 'Ichidan Verb',
  '率いる': 'Ichidan Verb',
  '引き下げる': 'Ichidan Verb',
  '引っ掛ける': 'Ichidan Verb',
  '深める': 'Ichidan Verb',
  '膨れる': 'Ichidan Verb',
  '老ける': 'Ichidan Verb',
  '不山戯る': 'Ichidan Verb',
  '震わせる': 'Ichidan Verb',
  '打付ける': 'Ichidan Verb',
  '経る': 'Ichidan Verb',
  '報じる': 'Ichidan Verb',
  '綻びる': 'Ichidan Verb',
  '滅びる': 'Ichidan Verb',
  'ぼやける': 'Ichidan Verb',
  '紛れる': 'Ichidan Verb',
  '交える': 'Ichidan Verb',
  '免れる': 'Ichidan Verb',
  '丸める': 'Ichidan Verb',
  '見掛ける': 'Ichidan Verb',
  '乱れる': 'Ichidan Verb',
  '結び付ける': 'Ichidan Verb',
  '目覚める': 'Ichidan Verb',
  '設ける': 'Ichidan Verb',
  '申し入れる': 'Ichidan Verb',
  '申し出る': 'Ichidan Verb',
  '凭れる': 'Ichidan Verb',
  '持てる': 'Ichidan Verb',
  '揉める': 'Ichidan Verb',
  '漏れる': 'Ichidan Verb',
  '休める': 'Ichidan Verb',
  'やっ付ける': 'Ichidan Verb',
  'やり遂げる': 'Ichidan Verb',
  '和らげる': 'Ichidan Verb',
  '茹でる': 'Ichidan Verb',
  '緩める': 'Ichidan Verb',
  '呼び止める': 'Ichidan Verb',
  '読み上げる': 'Ichidan Verb',
  '弱める': 'Ichidan Verb',
  'させる': 'Ichidan Verb',
  'ばれる': 'Ichidan Verb',
  '握り締める': 'Ichidan Verb',
  '委ねる': 'Ichidan Verb',
  'し過ぎる': 'Ichidan Verb',
  'し続ける': 'Ichidan Verb',
  '萎える': 'Ichidan Verb',
  '萎れる': 'Ichidan Verb',
  '惹かれる': 'Ichidan Verb',
  '応える': 'Ichidan Verb',
  '押し付ける': 'Ichidan Verb',
  '悔いる': 'Ichidan Verb',
  '戒める': 'Ichidan Verb',
  '垣間見る': 'Ichidan Verb',
  '割り当てる': 'Ichidan Verb',
  '干る': 'Ichidan Verb',
  '看る': 'Ichidan Verb',
  '戯れる': 'Ichidan Verb',
  '詰まらせる': 'Ichidan Verb',
  '虐げる': 'Ichidan Verb',
  '逆上せる': 'Ichidan Verb',
  '居合わせる': 'Ichidan Verb',
  '供える': 'Ichidan Verb',
  '狭める': 'Ichidan Verb',
  '繰り広げる': 'Ichidan Verb',
  '繰り上げる': 'Ichidan Verb',
  '群れる': 'Ichidan Verb',
  '決め付ける': 'Ichidan Verb',
  '兼ね備える': 'Ichidan Verb',
  '見違える': 'Ichidan Verb',
  '見捨てる': 'Ichidan Verb',
  '見上げる': 'Ichidan Verb',
  '見分ける': 'Ichidan Verb',
  '絞める': 'Ichidan Verb',
  '荒れる': 'Ichidan Verb',
  '呆ける': 'Ichidan Verb',
  '暈ける': 'Ichidan Verb',
  '惚れる': 'Ichidan Verb',
  '困り果てる': 'Ichidan Verb',
  '差し控える': 'Ichidan Verb',
  '差し伸べる': 'Ichidan Verb',
  '咲き乱れる': 'Ichidan Verb',
  '作り上げる': 'Ichidan Verb',
  '思われる': 'Ichidan Verb',
  '似せる': 'Ichidan Verb',
  '持ちこたえる': 'Ichidan Verb',
  '自惚れる': 'Ichidan Verb',
  '湿る': 'Ichidan Verb',
  '射る': 'Ichidan Verb',
  '射止める': 'Ichidan Verb',
  '煮詰める': 'Ichidan Verb',
  '手に入れる': 'Ichidan Verb',
  '手がける': 'Ichidan Verb',
  '修める': 'Ichidan Verb',
  '秀でる': 'Ichidan Verb',
  '充てる': 'Ichidan Verb',
  '従える': 'Ichidan Verb',
  '出すぎる': 'Ichidan Verb',
  '出遅れる': 'Ichidan Verb',
  '準える': 'Ichidan Verb',
  '初める': 'Ichidan Verb',
  '傷つける': 'Ichidan Verb',
  '照れる': 'Ichidan Verb',
  '上せる': 'Ichidan Verb',
  '乗じる': 'Ichidan Verb',
  '乗り越える': 'Ichidan Verb',
  '乗り遅れる': 'Ichidan Verb',
  '食い止める': 'Ichidan Verb',
  '食べ過ぎる': 'Ichidan Verb',
  '心がける': 'Ichidan Verb',
  '心得る': 'Ichidan Verb',
  '成し遂げる': 'Ichidan Verb',
  '盛り上げる': 'Ichidan Verb',
  '青ざめる': 'Ichidan Verb',
  '積み重ねる': 'Ichidan Verb',
  '先駆ける': 'Ichidan Verb',
  '奏でる': 'Ichidan Verb',
  '損ねる': 'Ichidan Verb',
  '打ち上げる': 'Ichidan Verb',
  '待ちかねる': 'Ichidan Verb',
  '待ち構える': 'Ichidan Verb',
  '待ち受ける': 'Ichidan Verb',
  '知れる': 'Ichidan Verb',
  '置き換える': 'Ichidan Verb',
  '築き上げる': 'Ichidan Verb',
  '着替える': 'Ichidan Verb',
  '低める': 'Ichidan Verb',
  '提げる': 'Ichidan Verb',
  '纏める': 'Ichidan Verb',
  '塗り替える': 'Ichidan Verb',
  '投じる': 'Ichidan Verb',
  '働きかける': 'Ichidan Verb',
  '動じる': 'Ichidan Verb',
  '禿げる': 'Ichidan Verb',
  '突き上げる': 'Ichidan Verb',
  '突き抜ける': 'Ichidan Verb',
  '敗れる': 'Ichidan Verb',
  '買い入れる': 'Ichidan Verb',
  '売り切れる': 'Ichidan Verb',
  '剥がれる': 'Ichidan Verb',
  '剥ける': 'Ichidan Verb',
  '薄れる': 'Ichidan Verb',
  '疲れ果てる': 'Ichidan Verb',
  '秘める': 'Ichidan Verb',
  '肥える': 'Ichidan Verb',
  '被せる': 'Ichidan Verb',
  '浮かれる': 'Ichidan Verb',
  '閉じ込める': 'Ichidan Verb',
  '弁える': 'Ichidan Verb',
  '報いる': 'Ichidan Verb',
  '翻る': 'Ichidan Verb',
  '埋もれる': 'Ichidan Verb',
  '名乗り出る': 'Ichidan Verb',
  '宥める': 'Ichidan Verb',
  '預け入れる': 'Ichidan Verb',
  '浴びせる': 'Ichidan Verb',
  '裏付ける': 'Ichidan Verb',
  '立ち上げる': 'Ichidan Verb',
  '立て替える': 'Ichidan Verb',
  '連れる': 'Ichidan Verb',
  '嘲る': 'Ichidan Verb',
  '嵌める': 'Ichidan Verb',
  '巫山戯る': 'Ichidan Verb',
  '舐める': 'Ichidan Verb',
  '褪せる': 'Ichidan Verb',
  '傾げる': 'Ichidan Verb',
  '選り分ける': 'Ichidan Verb',
  '束ねる': 'Ichidan Verb',
  '生ける': 'Ichidan Verb',
  '位置付ける': 'Ichidan Verb',
  '鋳る': 'Ichidan Verb',
  '印象付ける': 'Ichidan Verb',
  '打ち明ける': 'Ichidan Verb',
  '憂える': 'Ichidan Verb',
  '書き換える': 'Ichidan Verb',
  '駆けつける': 'Ichidan Verb',
  'かけ離れる': 'Ichidan Verb',
  '切り捨てる': 'Ichidan Verb',
  '極める': 'Ichidan Verb',
  '静める': 'Ichidan Verb',
  '途切れる': 'Ichidan Verb',
  '飛び降りる': 'Ichidan Verb',
  '捉える': 'Ichidan Verb',
  '囚われる': 'Ichidan Verb',
  '乗せる': 'Ichidan Verb',
  '貼り付ける': 'Ichidan Verb',
  '引き締める': 'Ichidan Verb',
  '引きつける': 'Ichidan Verb',
  '見かける': 'Ichidan Verb',
  '見比べる': 'Ichidan Verb',
  '見つめる': 'Ichidan Verb',
  '見届ける': 'Ichidan Verb',
  '閊える': 'Ichidan Verb',
  '追っかける': 'Ichidan Verb',
  '行き過ぎる': 'Ichidan Verb',
  '買い占める': 'Ichidan Verb',
  '近寄せる': 'Ichidan Verb',
  '千切れる': 'Ichidan Verb',
  '言い換える': 'Ichidan Verb',
  '惚ける': 'Ichidan Verb',
  '撥ねる': 'Ichidan Verb',
  '間に合わせる': 'Ichidan Verb',
  '縺れる': 'Ichidan Verb',
  '寝ぼける': 'Ichidan Verb',
  '頂ける': 'Ichidan Verb',
  '荒らげる': 'Ichidan Verb',
  '怒らせる': 'Ichidan Verb',
  '待たせる': 'Ichidan Verb',
  '書き上げる': 'Ichidan Verb',
  '取り揃える': 'Ichidan Verb',
  '取りまとめる': 'Ichidan Verb',
  '取り決める': 'Ichidan Verb',
  '追い上げる': 'Ichidan Verb',
  '洗い上げる': 'Ichidan Verb',
  '付いてる': 'Ichidan Verb',
  '封じる': 'Ichidan Verb',
  '身につける': 'Ichidan Verb',
  '利かせる': 'Ichidan Verb',
  '働かせる': 'Ichidan Verb',
  '萌える': 'Ichidan Verb',
  '余儀なくされる': 'Ichidan Verb',
  '目が覚める': 'Ichidan Verb',
  'そそられる': 'Ichidan Verb',
  '為れる': 'Ichidan Verb',
  '並び替える': 'Ichidan Verb',
  '報われる': 'Ichidan Verb',
  '抑える': 'Ichidan Verb',
  '様子を見る': 'Ichidan Verb',
  '救われる': 'Ichidan Verb',
  'できる': 'Ichidan Verb',
  '来る': 'Irregular Verb',
  'くる': 'Irregular Verb',
  'する': 'Irregular Verb',
  '愛する': 'Irregular Verb',
  '達する': 'Irregular Verb',
  '対する': 'Irregular Verb',
  '罰する': 'Irregular Verb',
  '関する': 'Irregular Verb',
  '適する': 'Irregular Verb',
  '接する': 'Irregular Verb',
  '属する': 'Irregular Verb',
  '熱する': 'Irregular Verb',
  '称する': 'Irregular Verb',
  '値する': 'Irregular Verb',
  '化する': 'Irregular Verb',
  '害する': 'Irregular Verb',
  '恋する': 'Irregular Verb',
  '察する': 'Irregular Verb',
  '制する': 'Irregular Verb',
  '即する': 'Irregular Verb',
  '脱する': 'Irregular Verb',
  '徹する': 'Irregular Verb',
  '反する': 'Irregular Verb',
  '面する': 'Irregular Verb',
  '有する': 'Irregular Verb',
  '要する': 'Irregular Verb',
  'お言いする': 'Irregular Verb',
  'お食べする': 'Irregular Verb',
  'お飲みする': 'Irregular Verb',
  '拝見する': 'Irregular Verb',
  'お聞きする': 'Irregular Verb',
  'お話する': 'Irregular Verb',
  'やって来る': 'Irregular Verb',
  '様にする': 'Irregular Verb',
  '科する': 'Irregular Verb',
  '課する': 'Irregular Verb',
  '画する': 'Irregular Verb',
  '喫する': 'Irregular Verb',
  '休する': 'Irregular Verb',
  '決する': 'Irregular Verb',
  '持ってくる': 'Irregular Verb',
  '発する': 'Irregular Verb',
  '表する': 'Irregular Verb',
  '保する': 'Irregular Verb',
  '擁する': 'Irregular Verb',
  '欲する': 'Irregular Verb',
  '揺する': 'Irregular Verb',
  '損する': 'Irregular Verb',
  '連れてくる': 'Irregular Verb',
  '得する': 'Irregular Verb',
  '資する': 'Irregular Verb',
  '題する': 'Irregular Verb',
  '付いてくる': 'Irregular Verb',
  '質問をする': 'Irregular Verb',
  'とする': 'Irregular Verb',
  '事にする': 'Irregular Verb',
  'しようとする': 'Irregular Verb',
  '度': 'Counter',
  '階': 'Counter',
  'ヶ月': 'Counter',
  '歳': 'Counter',
  '冊': 'Counter',
  '膳': 'Counter',
  '反': 'Counter',
  '着': 'Counter',
  '棟': 'Counter',
  '泊': 'Counter',
  '匹': 'Counter',
  '枚': 'Counter',
  '問': 'Counter',
  'カ国': 'Counter',
  '一つ': 'Counter',
  '二つ': 'Counter',
  '三つ': 'Counter',
  '四つ': 'Counter',
  '五つ': 'Counter',
  '六つ': 'Counter',
  '七つ': 'Counter',
  '八つ': 'Counter',
  '九つ': 'Counter',
  '一人': 'Counter',
  '二人': 'Counter',
  'いい': 'I-Adjective',
  'すごい': 'I-Adjective',
  '高い': 'I-Adjective',
  '安い': 'I-Adjective',
  '大きい': 'I-Adjective',
  '小さい': 'I-Adjective',
  '遠い': 'I-Adjective',
  '近い': 'I-Adjective',
  '悪い': 'I-Adjective',
  '楽しい': 'I-Adjective',
  'つまらない': 'I-Adjective',
  '強い': 'I-Adjective',
  '弱い': 'I-Adjective',
  '早い': 'I-Adjective',
  '速い': 'I-Adjective',
  '遅い': 'I-Adjective',
  '長い': 'I-Adjective',
  '短い': 'I-Adjective',
  '美味しい': 'I-Adjective',
  'うまい': 'I-Adjective',
  '可愛い': 'I-Adjective',
  '面白い': 'I-Adjective',
  'かわいい': 'I-Adjective',
  '新しい': 'I-Adjective',
  '良い': 'I-Adjective',
  '少ない': 'I-Adjective',
  '痛い': 'I-Adjective',
  '難しい': 'I-Adjective',
  '欲しい': 'I-Adjective',
  '多い': 'I-Adjective',
  '広い': 'I-Adjective',
  '古い': 'I-Adjective',
  '明るい': 'I-Adjective',
  '低い': 'I-Adjective',
  '白い': 'I-Adjective',
  '赤い': 'I-Adjective',
  '熱い': 'I-Adjective',
  '黒い': 'I-Adjective',
  '細い': 'I-Adjective',
  '甘い': 'I-Adjective',
  '薄い': 'I-Adjective',
  '太い': 'I-Adjective',
  '忙しい': 'I-Adjective',
  '丸い': 'I-Adjective',
  '若い': 'I-Adjective',
  '重い': 'I-Adjective',
  '円い': 'I-Adjective',
  '青い': 'I-Adjective',
  '辛い': 'I-Adjective',
  '軽い': 'I-Adjective',
  '冷たい': 'I-Adjective',
  '暖かい': 'I-Adjective',
  '厚い': 'I-Adjective',
  '暑い': 'I-Adjective',
  '涼しい': 'I-Adjective',
  '汚い': 'I-Adjective',
  '寒い': 'I-Adjective',
  '暗い': 'I-Adjective',
  '危ない': 'I-Adjective',
  '黄色い': 'I-Adjective',
  'まずい': 'I-Adjective',
  '狭い': 'I-Adjective',
  '易しい': 'I-Adjective',
  '温い': 'I-Adjective',
  'うるさい': 'I-Adjective',
  '美しい': 'I-Adjective',
  'おかしい': 'I-Adjective',
  '優しい': 'I-Adjective',
  '細かい': 'I-Adjective',
  '怖い': 'I-Adjective',
  '正しい': 'I-Adjective',
  '厳しい': 'I-Adjective',
  '苦い': 'I-Adjective',
  '深い': 'I-Adjective',
  '柔らかい': 'I-Adjective',
  '恥ずかしい': 'I-Adjective',
  '珍しい': 'I-Adjective',
  '眠い': 'I-Adjective',
  '悲しい': 'I-Adjective',
  '凄い': 'I-Adjective',
  '寂しい': 'I-Adjective',
  '硬い': 'I-Adjective',
  'ひどい': 'I-Adjective',
  '浅い': 'I-Adjective',
  '詳しい': 'I-Adjective',
  '素晴らしい': 'I-Adjective',
  '鋭い': 'I-Adjective',
  '激しい': 'I-Adjective',
  '苦しい': 'I-Adjective',
  '恐ろしい': 'I-Adjective',
  '貧しい': 'I-Adjective',
  '親しい': 'I-Adjective',
  '臭い': 'I-Adjective',
  '濃い': 'I-Adjective',
  '嬉しい': 'I-Adjective',
  '賢い': 'I-Adjective',
  'いけない': 'I-Adjective',
  'とんでもない': 'I-Adjective',
  'たまらない': 'I-Adjective',
  '等しい': 'I-Adjective',
  'きつい': 'I-Adjective',
  '可愛らしい': 'I-Adjective',
  '違いない': 'I-Adjective',
  '幼い': 'I-Adjective',
  '粗い': 'I-Adjective',
  '宜しい': 'I-Adjective',
  '力強い': 'I-Adjective',
  '危うい': 'I-Adjective',
  '懐かしい': 'I-Adjective',
  '四角い': 'I-Adjective',
  '薄暗い': 'I-Adjective',
  '悔しい': 'I-Adjective',
  '慌ただしい': 'I-Adjective',
  '憎い': 'I-Adjective',
  '怪しい': 'I-Adjective',
  '若々しい': 'I-Adjective',
  '醜い': 'I-Adjective',
  '険しい': 'I-Adjective',
  '申し訳ない': 'I-Adjective',
  '鈍い': 'I-Adjective',
  '荒い': 'I-Adjective',
  '恋しい': 'I-Adjective',
  'しょうがない': 'I-Adjective',
  '騒々しい': 'I-Adjective',
  '偉い': 'I-Adjective',
  'もったいない': 'I-Adjective',
  'しつこい': 'I-Adjective',
  '緩い': 'I-Adjective',
  '青白い': 'I-Adjective',
  '頼もしい': 'I-Adjective',
  '蒸し暑い': 'I-Adjective',
  '惜しい': 'I-Adjective',
  'くだらない': 'I-Adjective',
  'おめでたい': 'I-Adjective',
  '眩しい': 'I-Adjective',
  'めでたい': 'I-Adjective',
  '重たい': 'I-Adjective',
  'おとなしい': 'I-Adjective',
  '酸っぱい': 'I-Adjective',
  'かゆい': 'I-Adjective',
  'すまない': 'I-Adjective',
  'だらしない': 'I-Adjective',
  'みっともない': 'I-Adjective',
  'くどい': 'I-Adjective',
  'ありがたい': 'I-Adjective',
  'やかましい': 'I-Adjective',
  '思いがけない': 'I-Adjective',
  '清い': 'I-Adjective',
  'やむを得ない': 'I-Adjective',
  '茶色い': 'I-Adjective',
  '図々しい': 'I-Adjective',
  '勇ましい': 'I-Adjective',
  '騒がしい': 'I-Adjective',
  '甚だしい': 'I-Adjective',
  'ものすごい': 'I-Adjective',
  'めんどくさい': 'I-Adjective',
  '羨ましい': 'I-Adjective',
  'そそっかしい': 'I-Adjective',
  'バカらしい': 'I-Adjective',
  '厚かましい': 'I-Adjective',
  '塩辛い': 'I-Adjective',
  '煙い': 'I-Adjective',
  '憎らしい': 'I-Adjective',
  '狡い': 'I-Adjective',
  '目覚ましい': 'I-Adjective',
  '華々しい': 'I-Adjective',
  '際どい': 'I-Adjective',
  '相応しい': 'I-Adjective',
  '恩着せがましい': 'I-Adjective',
  'あくどい': 'I-Adjective',
  '浅ましい': 'I-Adjective',
  '呆気ない': 'I-Adjective',
  '荒っぽい': 'I-Adjective',
  '著しい': 'I-Adjective',
  '卑しい': 'I-Adjective',
  '厭やらしい': 'I-Adjective',
  '鬱陶しい': 'I-Adjective',
  '五月蝿い': 'I-Adjective',
  '可笑しい': 'I-Adjective',
  'おっかない': 'I-Adjective',
  '大人しい': 'I-Adjective',
  '難い': 'I-Adjective',
  '痒い': 'I-Adjective',
  '決まり悪い': 'I-Adjective',
  '擽ぐったい': 'I-Adjective',
  '下らない': 'I-Adjective',
  '諄い': 'I-Adjective',
  '汚らわしい': 'I-Adjective',
  '煙たい': 'I-Adjective',
  '心強い': 'I-Adjective',
  '心細い': 'I-Adjective',
  '快い': 'I-Adjective',
  '好ましい': 'I-Adjective',
  '渋い': 'I-Adjective',
  'しぶとい': 'I-Adjective',
  '清々しい': 'I-Adjective',
  'すばしこい': 'I-Adjective',
  '素早い': 'I-Adjective',
  '済まない': 'I-Adjective',
  '切ない': 'I-Adjective',
  '素っ気ない': 'I-Adjective',
  '逞しい': 'I-Adjective',
  '尊い': 'I-Adjective',
  '貴い': 'I-Adjective',
  '堪らない': 'I-Adjective',
  '容易い': 'I-Adjective',
  '怠い': 'I-Adjective',
  '詰らない': 'I-Adjective',
  'でかい': 'I-Adjective',
  '乏しい': 'I-Adjective',
  '情け深い': 'I-Adjective',
  '名高い': 'I-Adjective',
  '何気ない': 'I-Adjective',
  '生臭い': 'I-Adjective',
  '生温い': 'I-Adjective',
  '悩ましい': 'I-Adjective',
  '馴れ馴れしい': 'I-Adjective',
  '眠たい': 'I-Adjective',
  '望ましい': 'I-Adjective',
  '果ない': 'I-Adjective',
  '馬鹿馬鹿しい': 'I-Adjective',
  '馬鹿らしい': 'I-Adjective',
  '久しい': 'I-Adjective',
  '酷い': 'I-Adjective',
  '平たい': 'I-Adjective',
  '紛らわしい': 'I-Adjective',
  '不味い': 'I-Adjective',
  '待ち遠しい': 'I-Adjective',
  '真ん丸い': 'I-Adjective',
  '見苦しい': 'I-Adjective',
  '見すぼらしい': 'I-Adjective',
  '見っともない': 'I-Adjective',
  '空しい': 'I-Adjective',
  '物足りない': 'I-Adjective',
  '脆い': 'I-Adjective',
  '喧しい': 'I-Adjective',
  '易い': 'I-Adjective',
  '安っぽい': 'I-Adjective',
  '止むを得ない': 'I-Adjective',
  'ややこしい': 'I-Adjective',
  '好い': 'I-Adjective',
  '欲深い': 'I-Adjective',
  '煩わしい': 'I-Adjective',
  '敵わない': 'I-Adjective',
  'か弱い': 'I-Adjective',
  'ぎこちない': 'I-Adjective',
  '擽ったい': 'I-Adjective',
  '執拗い': 'I-Adjective',
  'しんどい': 'I-Adjective',
  'だらし無い': 'I-Adjective',
  'とんでも無い': 'I-Adjective',
  'やばい': 'I-Adjective',
  '愛しい': 'I-Adjective',
  '悪賢い': 'I-Adjective',
  '果てしない': 'I-Adjective',
  '忌まわしい': 'I-Adjective',
  '気持ちいい': 'I-Adjective',
  '輝かしい': 'I-Adjective',
  '疑わしい': 'I-Adjective',
  '興味深い': 'I-Adjective',
  '虚しい': 'I-Adjective',
  '計り知れない': 'I-Adjective',
  '潔い': 'I-Adjective',
  '嫌らしい': 'I-Adjective',
  '言うまでもない': 'I-Adjective',
  '限りない': 'I-Adjective',
  '古臭い': 'I-Adjective',
  '甲高い': 'I-Adjective',
  '黒っぽい': 'I-Adjective',
  '根強い': 'I-Adjective',
  '細長い': 'I-Adjective',
  '仕方がない': 'I-Adjective',
  '仕方ない': 'I-Adjective',
  '仕様がない': 'I-Adjective',
  '上手い': 'I-Adjective',
  '歯がゆい': 'I-Adjective',
  '手ごわい': 'I-Adjective',
  '手堅い': 'I-Adjective',
  '手早い': 'I-Adjective',
  '手痛い': 'I-Adjective',
  '重苦しい': 'I-Adjective',
  '女らしい': 'I-Adjective',
  '寝苦しい': 'I-Adjective',
  '心地よい': 'I-Adjective',
  '真新しい': 'I-Adjective',
  '瑞々しい': 'I-Adjective',
  '生ぬるい': 'I-Adjective',
  '切りがない': 'I-Adjective',
  '浅黒い': 'I-Adjective',
  '大人っぽい': 'I-Adjective',
  '嘆かわしい': 'I-Adjective',
  '淡い': 'I-Adjective',
  '男らしい': 'I-Adjective',
  '粘り強い': 'I-Adjective',
  '背が高い': 'I-Adjective',
  '煩い': 'I-Adjective',
  '否めない': 'I-Adjective',
  '幅広い': 'I-Adjective',
  '物凄い': 'I-Adjective',
  '無い': 'I-Adjective',
  '名残惜しい': 'I-Adjective',
  '面倒くさい': 'I-Adjective',
  '尤もらしい': 'I-Adjective',
  '有難い': 'I-Adjective',
  '用心深い': 'I-Adjective',
  '頼りない': 'I-Adjective',
  '涙ぐましい': 'I-Adjective',
  '格好いい': 'I-Adjective',
  '気難しい': 'I-Adjective',
  '香ばしい': 'I-Adjective',
  '芳しい': 'I-Adjective',
  '肌寒い': 'I-Adjective',
  '味気ない': 'I-Adjective',
  '荒々しい': 'I-Adjective',
  '凄まじい': 'I-Adjective',
  '情けない': 'I-Adjective',
  '生々しい': 'I-Adjective',
  '儚い': 'I-Adjective',
  '勿体ない': 'I-Adjective',
  '分かりにくい': 'I-Adjective',
  '目出度い': 'I-Adjective',
  '痛ましい': 'I-Adjective',
  '湿っぽい': 'I-Adjective',
  '注意深い': 'I-Adjective',
  '端たない': 'I-Adjective',
  '水臭い': 'I-Adjective',
  '申し分ない': 'I-Adjective',
  'やり切れない': 'I-Adjective',
  '喜ばしい': 'I-Adjective',
  '読みにくい': 'I-Adjective',
  '余儀ない': 'I-Adjective',
  '金がない': 'I-Adjective',
  '暇がない': 'I-Adjective',
  '役に立たない': 'I-Adjective',
  'どうしようも無い': 'I-Adjective',
  '気持ち悪い': 'I-Adjective',
  '間違いない': 'I-Adjective',
  '数少ない': 'I-Adjective',
  '訳がない': 'I-Adjective',
  'どうでも良い': 'I-Adjective',
  '紛れもない': 'I-Adjective',
  'それらしい': 'I-Adjective',
  'あり得ない': 'I-Adjective',
  '如何にもならない': 'I-Adjective',
  '大っきい': 'I-Adjective',
  'すっごい': 'I-Adjective',
  '言いようがない': 'I-Adjective',
  'どこにも無い': 'I-Adjective',
  'ない': 'I-Adjective',
  '有って無い': 'I-Adjective',
  'つまんない': 'I-Adjective',
  '何とも言えない': 'I-Adjective',
  '問題ない': 'I-Adjective',
  '気持ちがいい': 'I-Adjective',
  '事': 'Noun',
  '時': 'Noun',
  '時間': 'Noun',
  '人': 'Noun',
  '人間': 'Noun',
  '今': 'Noun',
  '所': 'Noun',
  '中': 'Noun',
  '外': 'Noun',
  '右': 'Noun',
  '左': 'Noun',
  '上': 'Noun',
  '下': 'Noun',
  '後': 'Noun',
  '前': 'Noun',
  '為': 'Noun',
  '場合': 'Noun',
  '日本': 'Noun',
  'イギリス': 'Noun',
  '国': 'Noun',
  '子供': 'Noun',
  '仕事': 'Noun',
  '次': 'Noun',
  '体': 'Noun',
  '目': 'Noun',
  '手': 'Noun',
  '足': 'Noun',
  '腕': 'Noun',
  '頭': 'Noun',
  '言葉': 'Noun',
  '意味': 'Noun',
  '家': 'Noun',
  '部屋': 'Noun',
  '居間': 'Noun',
  '床': 'Noun',
  '壁': 'Noun',
  '猫': 'Noun',
  '犬': 'Noun',
  '馬': 'Noun',
  '男': 'Noun',
  '女': 'Noun',
  '形': 'Noun',
  '間': 'Noun',
  '最初': 'Noun',
  '最後': 'Noun',
  '気持ち': 'Noun',
  '友達': 'Noun',
  '今日': 'Noun',
  '昨日': 'Noun',
  '明日': 'Noun',
  '明後日': 'Noun',
  '朝': 'Noun',
  '昼': 'Noun',
  '夜': 'Noun',
  '生活': 'Noun',
  '車': 'Noun',
  '電気': 'Noun',
  '電車': 'Noun',
  '心': 'Noun',
  '会社': 'Noun',
  '学校': 'Noun',
  '大学': 'Noun',
  '学生': 'Noun',
  '先生': 'Noun',
  '場所': 'Noun',
  '店': 'Noun',
  '今度': 'Noun',
  '水': 'Noun',
  '土': 'Noun',
  '火': 'Noun',
  '世界': 'Noun',
  '家族': 'Noun',
  'お母さん': 'Noun',
  'お父さん': 'Noun',
  '本': 'Noun',
  '毎日': 'Noun',
  '毎年': 'Noun',
  '勉強': 'Noun',
  '説明': 'Noun',
  '質問': 'Noun',
  '電話': 'Noun',
  '写真': 'Noun',
  '全部': 'Noun',
  '文章': 'Noun',
  '問題': 'Noun',
  '旅行': 'Noun',
  '家庭': 'Noun',
  '番号': 'Noun',
  '今年': 'Noun',
  '結婚': 'Noun',
  '新聞': 'Noun',
  '名前': 'Noun',
  '映画': 'Noun',
  'ページ': 'Noun',
  'スポーツ': 'Noun',
  '後ろ': 'Noun',
  '料理': 'Noun',
  '音楽': 'Noun',
  '買い物': 'Noun',
  '時計': 'Noun',
  '道': 'Noun',
  '年': 'Noun',
  '海': 'Noun',
  '花': 'Noun',
  '色': 'Noun',
  '銀行': 'Noun',
  '自動車': 'Noun',
  '黒': 'Noun',
  '北': 'Noun',
  '西': 'Noun',
  '南': 'Noun',
  'ニュース': 'Noun',
  '声': 'Noun',
  '庭': 'Noun',
  '青': 'Noun',
  '地図': 'Noun',
  '自転車': 'Noun',
  '女の子': 'Noun',
  '町': 'Noun',
  '春': 'Noun',
  '英語': 'Noun',
  '話': 'Noun',
  '箱': 'Noun',
  '病院': 'Noun',
  '半': 'Noun',
  '雑誌': 'Noun',
  '机': 'Noun',
  '動物': 'Noun',
  '外国': 'Noun',
  '財布': 'Noun',
  '服': 'Noun',
  '教室': 'Noun',
  '公園': 'Noun',
  '歌': 'Noun',
  '村': 'Noun',
  '私': 'Noun',
  'あなた': 'Noun',
  '何': 'Noun',
  'これ': 'Noun',
  'それ': 'Noun',
  'あれ': 'Noun',
  'どれ': 'Noun',
  'ここ': 'Noun',
  'そこ': 'Noun',
  'あそこ': 'Noun',
  'どこ': 'Noun',
  '自分': 'Noun',
  '彼': 'Noun',
  '彼女': 'Noun',
  '誰': 'Noun',
  '十': 'Noun',
  '四': 'Noun',
  '六': 'Noun',
  '八': 'Noun',
  '七': 'Noun',
  '百': 'Noun',
  '千': 'Noun',
  '九': 'Noun',
  'みんな': 'Noun',
  'やはり': 'Adverb',
  'また': 'Adverb',
  'まだ': 'Adverb',
  'とても': 'Adverb',
  '少し': 'Adverb',
  'まず': 'Adverb',
  'あまり': 'Adverb',
  '例えば': 'Adverb',
  '特に': 'Adverb',
  '結局': 'Adverb',
  '多分': 'Adverb',
  'よく': 'Adverb',
  'もっと': 'Adverb',
  '最近': 'Adverb',
};

String wordTypeFor(String japanese) => kWordTypes[japanese] ?? '';
